const assert=require('assert');
const alerts=require('../lib/alert-stress');
function opportunity(resale={}){return{retailer:'Best Buy',sku:'TEST-1',price:100,observedAt:new Date().toISOString(),flipScore:92,evidenceQuality:.95,anomaly:{confidence:92,label:'Extreme Deal'},priceBaseline:{confidence:88},economics:{profit:120,roi:95},downsideEconomics:{profit:80,roi:62,safetyMarginPct:30},riskAdjustedEconomics:{profit:70,roi:55},purchaseDecision:{headroomPct:30},risk:{priceStability:{stabilityScore:90},liquidation:{economics:{profit:55,roi:45}}},resale:{marketValue:300,conservativeValue:280,askingMedian:295,resaleConfidence:90,competitionRatio:.2,momentumPct:3,spreadPct:5,estimatedDaysToSell:7,liquidityScore:90,...resale},inventory:{quantity:3,verified:true,pickupAvailable:true},feeRate:.135,shipping:10,taxRate:.06,holdingCostPerDay:.1};}
const strong=alerts.shouldAlert(opportunity());assert.equal(strong.alert,true);assert(strong.stressAssessment);assert(strong.fulfillmentAssessment&&strong.fulfillmentAssessment.confidence>=80);assert(strong.expectedEconomics.expectedProfit>0);
const crowded=alerts.shouldAlert(opportunity({marketValue:150,conservativeValue:135,askingMedian:145,resaleConfidence:35,competitionRatio:4,momentumPct:-25,spreadPct:45}));assert.equal(crowded.alert,false);assert(crowded.reasons.includes('stress-profit')||crowded.reasons.includes('stress-roi'));
const uncertain=opportunity();uncertain.fulfillmentConfidence=30;uncertain.inventory={quantity:1};const uncertainDecision=alerts.shouldAlert(uncertain);assert.equal(uncertainDecision.alert,false);assert(uncertainDecision.reasons.includes('fulfillment-confidence'));assert(uncertainDecision.expectedEconomics.expectedProfit<strong.economics?.profit||uncertainDecision.expectedEconomics.expectedProfit<120);
const soldOut=opportunity();soldOut.inventory={quantity:0,verified:true};const soldOutDecision=alerts.shouldAlert(soldOut);assert.equal(soldOutDecision.alert,false);assert(soldOutDecision.reasons.includes('inventory-unavailable'));
const multi=opportunity();multi.exitChannels=[{name:'eBay-like',feeRate:.15,shipping:12,confidence:90},{name:'Local',feeRate:0,shipping:0,salePrice:250,confidence:80,holdingDays:3}];const multiDecision=alerts.shouldAlert(multi);assert.equal(multiDecision.alert,true);assert(multiDecision.channelAssessment&&multiDecision.channelAssessment.best);
const thin=opportunity();thin.exitChannels=[{name:'Thin exit',feeRate:.1,shipping:0,salePrice:130,confidence:95,holdingDays:1}];const thinDecision=alerts.shouldAlert(thin,{minExitProfit:0,minExitRoi:0});assert.equal(thinDecision.alert,false);assert(thinDecision.reasons.includes('exit-safety'));
const noMargin=opportunity();noMargin.exitChannels=[{name:'Bad venue',feeRate:.5,shipping:100,salePrice:130,confidence:90}];const blocked=alerts.shouldAlert(noMargin);assert.equal(blocked.alert,false);assert(blocked.reasons.includes('exit-profit')||blocked.reasons.includes('exit-roi'));
const first=alerts.shouldNotify(multi,null,{now:Date.now()});assert.equal(first.notify,true);const changed={...multi,exitChannels:[{name:'Local',feeRate:0,shipping:0,salePrice:285,confidence:95,holdingDays:2}]};const second=alerts.shouldNotify(changed,{fingerprint:first.fingerprint,priority:first.decision.priority,notifiedAt:new Date().toISOString()},{now:Date.now()});assert.equal(second.notify,true);assert.equal(second.reason,'state-changed');
const fulfillmentChanged={...multi,fulfillmentConfidence:60,inventory:{quantity:2}};const third=alerts.shouldNotify(fulfillmentChanged,{fingerprint:first.fingerprint,priority:first.decision.priority,notifiedAt:new Date().toISOString()},{now:Date.now()});assert.equal(third.notify,true);assert.equal(third.reason,'state-changed','material fulfillment changes should refresh the alert');
const ranked=alerts.rankAlerts([opportunity(),opportunity({marketValue:260,conservativeValue:240,askingMedian:250,resaleConfidence:80})]);assert.equal(ranked.length,2);assert(ranked[0].decision.stressAssessment);
console.log('alert stress tests passed');