const assert=require('assert');
const alerts=require('../lib/alert-stress');
function opportunity(resale={}){return{retailer:'Best Buy',sku:'TEST-1',price:100,observedAt:new Date().toISOString(),flipScore:92,evidenceQuality:.95,anomaly:{confidence:92,label:'Extreme Deal'},priceBaseline:{confidence:88},economics:{profit:120,roi:95},downsideEconomics:{profit:80,roi:62,safetyMarginPct:30},riskAdjustedEconomics:{profit:70,roi:55},purchaseDecision:{headroomPct:30},risk:{priceStability:{stabilityScore:90},liquidation:{economics:{profit:55,roi:45}}},resale:{marketValue:300,conservativeValue:280,askingMedian:295,resaleConfidence:90,competitionRatio:.2,momentumPct:3,spreadPct:5,estimatedDaysToSell:7,liquidityScore:90,...resale},feeRate:.135,shipping:10,taxRate:.06,holdingCostPerDay:.1};}
const strong=alerts.shouldAlert(opportunity());
assert.equal(strong.alert,true);
assert(strong.stressAssessment);
assert(strong.stressAssessment.stressEconomics.profit>=20);
const crowded=alerts.shouldAlert(opportunity({marketValue:150,conservativeValue:135,askingMedian:145,resaleConfidence:35,competitionRatio:4,momentumPct:-25,spreadPct:45}));
assert.equal(crowded.alert,false);
assert(crowded.reasons.includes('stress-profit')||crowded.reasons.includes('stress-roi'));
const multi=opportunity();multi.exitChannels=[{name:'eBay-like',feeRate:.15,shipping:12,confidence:90},{name:'Local',feeRate:0,shipping:0,salePrice:250,confidence:80,holdingDays:3}];
const multiDecision=alerts.shouldAlert(multi);assert.equal(multiDecision.alert,true);assert(multiDecision.channelAssessment&&multiDecision.channelAssessment.best,'alerts should expose best resale exit');
const thin=opportunity();thin.exitChannels=[{name:'Thin exit',feeRate:.1,shipping:0,salePrice:130,confidence:95,holdingDays:1}];
const thinDecision=alerts.shouldAlert(thin,{minExitProfit:0,minExitRoi:0});assert.equal(thinDecision.alert,false);assert(thinDecision.reasons.includes('exit-safety'),'positive profit alone must not pass when break-even safety is too thin');
const noMargin=opportunity();noMargin.exitChannels=[{name:'Bad venue',feeRate:.5,shipping:100,salePrice:130,confidence:90}];
const blocked=alerts.shouldAlert(noMargin);assert.equal(blocked.alert,false);assert(blocked.reasons.includes('exit-profit')||blocked.reasons.includes('exit-roi'),'an otherwise strong deal must be blocked when no configured exit preserves margin');
const first=alerts.shouldNotify(multi,null,{now:Date.now()});assert.equal(first.notify,true);const changed={...multi,exitChannels:[{name:'Local',feeRate:0,shipping:0,salePrice:285,confidence:95,holdingDays:2}]};const second=alerts.shouldNotify(changed,{fingerprint:first.fingerprint,priority:first.decision.priority,notifiedAt:new Date().toISOString()},{now:Date.now()});assert.equal(second.notify,true);assert.equal(second.reason,'state-changed','material exit-channel improvement should refresh the alert');
const ranked=alerts.rankAlerts([opportunity(),opportunity({marketValue:260,conservativeValue:240,askingMedian:250,resaleConfidence:80})]);
assert.equal(ranked.length,2);
assert(ranked[0].decision.stressAssessment);
console.log('alert stress tests passed');