const assert=require('assert');
const {fingerprint,shouldSendAlert}=require('../lib/alert-dedupe');
const base={retailer:'Home Depot',storeId:'1234',opportunityId:'sku-9',alertLevel:'instant',alertEligible:true,price:100,profit:40};
const key=fingerprint(base);
assert.strictEqual(key,'home depot|1234|sku-9|instant');
let result=shouldSendAlert({candidate:base,previous:null,asOf:'2026-09-01T16:00:00Z'});
assert.strictEqual(result.send,true);
assert.strictEqual(result.reason,'first-alert');
result=shouldSendAlert({candidate:base,previous:{fingerprint:key,sentAt:'2026-09-01T15:00:00Z',price:100,profit:40},asOf:'2026-09-01T16:00:00Z',cooldownMinutes:180});
assert.strictEqual(result.send,false);
assert.strictEqual(result.reason,'cooldown');
result=shouldSendAlert({candidate:{...base,price:95},previous:{fingerprint:key,sentAt:'2026-09-01T15:30:00Z',price:100,profit:40},asOf:'2026-09-01T16:00:00Z'});
assert.strictEqual(result.send,true);
assert.strictEqual(result.reason,'price-improved');
result=shouldSendAlert({candidate:{...base,profit:44},previous:{fingerprint:key,sentAt:'2026-09-01T15:30:00Z',price:100,profit:40},asOf:'2026-09-01T16:00:00Z'});
assert.strictEqual(result.send,true);
assert.strictEqual(result.reason,'profit-improved');
result=shouldSendAlert({candidate:base,previous:{fingerprint:key,sentAt:'2026-09-01T10:00:00Z',price:100,profit:40},asOf:'2026-09-01T16:00:00Z',cooldownMinutes:180});
assert.strictEqual(result.send,true);
assert.strictEqual(result.reason,'cooldown-expired');
result=shouldSendAlert({candidate:{...base,alertEligible:false},previous:null});
assert.strictEqual(result.send,false);
assert.strictEqual(result.reason,'not-eligible');
console.log('alert dedupe tests passed');