const assert=require('assert');
const {assessMaterialChange,decideRepeatAlert}=require('../lib/alert-material-change');
const previous={price:100,profit:40,roi:80,confidence:.86,anomalyScore:.82,historySampleCount:20,resaleMedian:150,resaleEffectiveWeight:8,recommendedQuantity:2,availableQuantity:5,alertLevel:'instant',alertEligible:true,sentAt:'2026-09-03T00:00:00Z'};
let a=assessMaterialChange({candidate:{...previous,price:96},previous});
assert.strictEqual(a.materiallyChanged,true);
assert(a.reasons.includes('price-drop'));
a=assessMaterialChange({candidate:{...previous,profit:41,roi:81},previous});
assert.strictEqual(a.materiallyChanged,false);
a=assessMaterialChange({candidate:{...previous,recommendedQuantity:3},previous});
assert.strictEqual(a.materiallyChanged,true);
assert(a.reasons.includes('recommended-quantity-change'));
a=assessMaterialChange({candidate:{...previous,confidence:.74},previous});
assert.strictEqual(a.materiallyChanged,true);
assert(a.reasons.includes('confidence-change'));
a=assessMaterialChange({candidate:{...previous,anomalyScore:.91},previous});
assert.strictEqual(a.materiallyChanged,true);
assert(a.reasons.includes('anomaly-score-change'));
a=assessMaterialChange({candidate:{...previous,historySampleCount:25},previous});
assert.strictEqual(a.materiallyChanged,true);
assert(a.reasons.includes('price-history-depth-change'));
a=assessMaterialChange({candidate:{...previous,resaleEffectiveWeight:10.5},previous});
assert.strictEqual(a.materiallyChanged,true);
assert(a.reasons.includes('resale-evidence-change'));
let d=decideRepeatAlert({candidate:{...previous},previous,asOf:'2026-09-03T04:00:00Z',cooldownMinutes:180});
assert.strictEqual(d.send,false);
assert.strictEqual(d.reason,'unchanged-after-cooldown');
d=decideRepeatAlert({candidate:{...previous,price:96},previous,asOf:'2026-09-03T01:00:00Z'});
assert.strictEqual(d.send,true);
assert.strictEqual(d.reason,'material-change');
d=decideRepeatAlert({candidate:{...previous},previous,asOf:'2026-09-04T01:00:00Z',reminderHours:24});
assert.strictEqual(d.send,true);
assert.strictEqual(d.reason,'long-window-reminder');
d=decideRepeatAlert({candidate:{...previous,alertEligible:false},previous,asOf:'2026-09-03T01:00:00Z'});
assert.strictEqual(d.send,false);
assert.strictEqual(d.reason,'not-eligible');
console.log('alert material-change tests passed');