const assert=require('assert');
const quality=require('../lib/comp-quality');
const alerts=require('../lib/alert-outcome');
const retail={title:'Sony WH-1000XM6 Wireless Headphones',brand:'Sony',model:'WH1000XM6',upc:'027242930292'};
const sold=(price,extra={})=>({title:'Sony WH-1000XM6 Wireless Headphones',brand:'Sony',model:'WH1000XM6',upc:'027242930292',price,evidenceType:'verified sold',...extra});
const strong=[sold(399),sold(389),sold(405),sold(395),sold(410),{...sold(420),evidenceType:'active asking'}];
const a=quality.assess(retail,strong);
assert(a.confidence>=80,'strong exact sold evidence should be high confidence');
assert.strictEqual(a.soldCount,5);
assert.strictEqual(a.rejected,0);
const contaminated=[sold(399),{title:'Sony WH-1000XM5 Bundle with Case',brand:'Sony',model:'WH1000XM5',upc:'027242923690',price:520,evidenceType:'verified sold'},{title:'Sony WH-1000XM6',brand:'Sony',model:'WH1000XM6',upc:'027242930292',price:499,evidenceType:'active asking'}];
const b=quality.assess(retail,contaminated);
assert(b.rejected>=1,'mismatched SKU must be rejected');
assert(b.soldCount<2,'thin sold evidence must remain thin');
const adj=quality.adjustEconomics({profit:100,roi:50},b);
assert(adj.compAdjustedProfit<100&&adj.compAdjustedRoi<50,'weak comps must haircut economics');
const base={id:'x',title:retail.title,retailProduct:retail,resaleComps:contaminated,currentPrice:200,price:200,flipScore:95,confidence:95,anomaly:{confidence:95},resale:{resaleConfidence:90,sold7:10,sold30:30,sold90:80,activeCount:4},economics:{profit:100,roi:50,totalInvested:200},risk:{liquidation:{economics:{profit:20}}},availability:'in stock',fulfillment:{status:'available',confidence:95}};
const d=alerts.shouldAlert(base,{minProfit:0,minRoi:0,minConfidence:0,minFlipScore:0,minStressProfit:-999,minStressRoi:-999,minFreshnessConfidence:0,minFreshnessAdjustedProfit:-999,minFreshnessAdjustedRoi:-999,minFulfillmentConfidence:0,minExpectedProfit:-999,minExpectedRoi:-999,minSellThroughPct:0,minSellThroughExpectedProfit:-999,minSellThroughExpectedRoi:-999,maxExpectedDaysToSell:999,minCapitalVelocityScore:0,minCompConfidence:60,minVerifiedSoldComps:2,minCompAdjustedProfit:-999,minCompAdjustedRoi:-999});
assert(d.reasons.includes('verified-sold-comps'),'alert must require verified sold depth');
console.log('comp-quality tests passed');