const assert=require('assert');
const quality=require('../lib/comp-quality');
const alerts=require('../lib/alert-outcome');
const now=Date.parse('2026-08-31T10:00:00Z');
const retail={title:'Sony WH-1000XM6 Wireless Headphones',brand:'Sony',model:'WH1000XM6',upc:'027242930292'};
const sold=(price,days)=>({title:retail.title,brand:'Sony',model:'WH1000XM6',upc:retail.upc,price,evidenceType:'verified sold',soldAt:new Date(now-days*864e5).toISOString()});
const fresh=[sold(399,2),sold(389,7),sold(405,18),sold(395,35)];
const stale=[sold(399,120),sold(389,150),sold(405,180),sold(395,210)];
const a=quality.assess(retail,fresh,{now});
const b=quality.assess(retail,stale,{now});
assert.strictEqual(a.freshSoldCount,4,'recent sold comps should count as fresh');
assert.strictEqual(b.freshSoldCount,0,'old sold comps should not count as fresh');
assert.strictEqual(b.staleSoldCount,4,'90+ day sold comps should be explicitly stale');
assert(a.freshnessScore>b.freshnessScore,'fresh evidence must score above stale evidence');
assert(a.confidence>b.confidence,'freshness should affect comp confidence');
const base={id:'freshness',title:retail.title,retailProduct:retail,resaleComps:stale,currentPrice:200,price:200,flipScore:95,confidence:95,anomaly:{confidence:95},resale:{resaleConfidence:90,sold7:10,sold30:30,sold90:80,activeCount:4},economics:{profit:100,roi:50,totalInvested:200},risk:{liquidation:{economics:{profit:20}}},availability:'in stock',fulfillment:{status:'available',confidence:95}};
const d=alerts.shouldAlert(base,{now,minProfit:0,minRoi:0,minConfidence:0,minFlipScore:0,minStressProfit:-999,minStressRoi:-999,minFreshnessConfidence:0,minFreshnessAdjustedProfit:-999,minFreshnessAdjustedRoi:-999,minFulfillmentConfidence:0,minExpectedProfit:-999,minExpectedRoi:-999,minSellThroughPct:0,minSellThroughExpectedProfit:-999,minSellThroughExpectedRoi:-999,maxExpectedDaysToSell:999,minCapitalVelocityScore:0,minCompConfidence:0,minVerifiedSoldComps:0,minFreshSoldComps:2,minCompFreshness:45,minCompAdjustedProfit:-999,minCompAdjustedRoi:-999});
assert(d.reasons.includes('fresh-sold-comps'),'alerts must reject stale sold depth');
assert(d.reasons.includes('comp-freshness'),'alerts must reject stale comparison sets');
const fpOld=quality.fingerprint(retail,stale,{now});
const fpNew=quality.fingerprint(retail,fresh,{now});
assert.notStrictEqual(fpOld,fpNew,'freshness changes must alter alert fingerprint state');
console.log('comp-freshness tests passed');