'use strict';
const assert=require('assert');
const {customerAuthorityDisposition,classifyOpportunityData,partitionCustomerOpportunities}=require('../lib/pwa-data-state');
const asOf='2026-09-05T11:00:00.000Z';
const complete={historyAuthoritative:true,anomalyAuthoritative:true,marketComparisonAuthoritative:true,profitRoiAuthoritative:true,notificationAuthoritative:true};
const incomplete={...complete,marketComparisonAuthoritative:false,profitRoiAuthoritative:false,notificationAuthoritative:false};
const authorized={id:'authorized',dataOrigin:'live',validationState:'validated',observedAt:'2026-09-05T10:30:00.000Z',evidenceAuthority:complete};
const withheld={id:'withheld',dataOrigin:'live',validationState:'validated',observedAt:'2026-09-05T10:30:00.000Z',referencePrice:999,customerProfit:500,customerRoi:400,comps:{d30:899,d60:875,d90:849},evidenceAuthority:incomplete};
assert.deepEqual(customerAuthorityDisposition(authorized),{present:true,complete:true,missing:[]});
const withheldAuthority=customerAuthorityDisposition(withheld);
assert.equal(withheldAuthority.complete,false);
assert(withheldAuthority.missing.includes('marketComparisonAuthoritative'));
assert(withheldAuthority.missing.includes('profitRoiAuthoritative'));
const authorizedState=classifyOpportunityData(authorized,{asOf});
assert.equal(authorizedState.kind,'live');
assert.equal(authorizedState.customerVisible,true);
assert.equal(authorizedState.alertEligible,true);
const withheldState=classifyOpportunityData(withheld,{asOf});
assert.equal(withheldState.kind,'validation');
assert.equal(withheldState.customerVisible,false);
assert.equal(withheldState.alertEligible,false);
assert(withheldState.reason.startsWith('customer-authority-incomplete:'));
const missingEnvelope={id:'missing-envelope',dataOrigin:'live',validationState:'validated',observedAt:'2026-09-05T10:30:00.000Z',referencePrice:999,customerProfit:500,customerRoi:400,comps:{d30:899,d60:875,d90:849}};
const missingState=classifyOpportunityData(missingEnvelope,{asOf});
assert.equal(missingState.kind,'validation');
assert.equal(missingState.customerVisible,false,'validated live rows without an authority envelope must fail closed');
assert.equal(missingState.alertEligible,false);
assert.equal(missingState.reason,'customer-authority-missing');
const cachedMissing=classifyOpportunityData({...missingEnvelope,id:'cached-missing',dataOrigin:'cached'},{asOf});
assert.equal(cachedMissing.customerVisible,false,'cached customer rows must also carry an authority envelope');
assert.equal(cachedMissing.reason,'customer-authority-missing');
const demo=classifyOpportunityData({id:'demo',dataOrigin:'demo',observedAt:'2026-09-05T10:30:00.000Z'},{asOf});
assert.equal(demo.customerVisible,true,'demo rows remain usable without production authority');
assert.equal(demo.alertEligible,false);
const groups=partitionCustomerOpportunities([authorized,withheld,missingEnvelope],{asOf});
assert.deepEqual(groups.live.map(x=>x.id),['authorized']);
assert.deepEqual(groups.hidden.map(x=>x.id),['withheld','missing-envelope']);
console.log('customer PWA authority gate tests passed');
