const assert=require('assert');
global.HuntIQExplain=require('../lib/deal-explain');
global.HuntIQCustomerCard=require('../lib/customer-card');
const Feed=require('../lib/customer-feed');
const now=Date.parse('2026-09-01T05:00:00Z');
const strong={title:'Tool Kit',retailer:'Home Depot',storeId:'18360',zip:'18360',channel:'store',source:'retailer-live',verified:true,observedAt:'2026-09-01T04:55:00Z',price:49.03,economics:{profit:72,roi:147},riskAdjustedEconomics:{roi:88},downsideEconomics:{roi:41},resale:{marketValue:155,resaleConfidence:82},purchaseDecision:{verdict:'STRONG BUY',maxBuyPrice:61},quantityEconomics:{plannedUnits:3,expectedLotProfit:216},readiness:{ready:true,readinessScore:88,historySampleCount:12,historySpanDays:30,reasons:[]},risk:{stabilityAdjustedAnomalyConfidence:91},alert:{alert:true}};
const thin={...strong,title:'Thin history',readiness:{ready:false,readinessScore:35,historySampleCount:2,historySpanDays:3,reasons:['price-history-thin']}};
const stale={...strong,title:'Stale price',observedAt:'2026-09-01T00:00:00Z'};
const unverified={...strong,title:'Community lead',source:'community',verified:false,alert:{alert:true}};
let ranked=Feed.rankFeed([thin,strong,stale,unverified],{now,staleAfterMinutes:120});
assert.equal(ranked[0].title,'Tool Kit');
assert.equal(ranked[0].state,'STRONG BUY');
assert.equal(ranked[0].alertEligible,true);
const wait=ranked.find(x=>x.title==='Thin history');assert.equal(wait.state,'WAIT');assert.ok(wait.huntiqScore<=49);assert.equal(wait.alertEligible,false);
const old=ranked.find(x=>x.title==='Stale price');assert.equal(old.freshness.stale,true);assert.equal(old.alertEligible,false);assert.ok(old.huntiqScore<ranked[0].huntiqScore);
const lead=ranked.find(x=>x.title==='Community lead');assert.equal(lead.source.verified,false);assert.ok(lead.huntiqScore<ranked[0].huntiqScore);
const buckets=Feed.feedBuckets([strong,thin,stale],{now,staleAfterMinutes:120});assert.equal(buckets.topPicks.length,2);assert.equal(buckets.watch.length,1);assert.equal(buckets.alerts.length,1);
assert.ok(Feed.historySignal(strong)>Feed.historySignal(thin));
console.log('customer-feed tests passed');