'use strict';
const assert=require('assert');
const {deriveCustomerEvidenceAuthority,customerAuthorityDisposition,classifyOpportunityData,partitionCustomerOpportunities}=require('../lib/pwa-data-state');
const asOf='2026-09-05T11:00:00.000Z';
const complete={historyAuthoritative:true,anomalyAuthoritative:true,marketComparisonAuthoritative:true,profitRoiAuthoritative:true,notificationAuthoritative:true};
const incomplete={...complete,marketComparisonAuthoritative:false,profitRoiAuthoritative:false,notificationAuthoritative:false};
const verifiedHistory=[1,2,3].map(n=>({verified:true,price:70+n}));
const verifiedSales=[1,2,3].map(n=>({verified:true,price:90+n,status:'sold'}));
const liveReadiness={historyReady:true,resaleReady:true,releaseReady:true,economicsReady:true,anomalyConfidence:88,conservativeProfit:42,conservativeRoi:71,alertEligible:true};
const authorized={id:'authorized',dataOrigin:'live',validationState:'validated',observedAt:'2026-09-05T10:30:00.000Z',referencePrice:79,priceHistoryObservations:verifiedHistory,completedSales:verifiedSales,comps:{authoritative:true,d30:92,d60:91,d90:90},liveReadiness,evidenceAuthority:complete};
const withheld={id:'withheld',dataOrigin:'live',validationState:'validated',observedAt:'2026-09-05T10:30:00.000Z',referencePrice:999,customerProfit:500,customerRoi:400,comps:{d30:899,d60:875,d90:849},evidenceAuthority:incomplete};
const derived=deriveCustomerEvidenceAuthority(authorized);
assert.equal(derived.historyAuthoritative,true);
assert.equal(derived.marketComparisonAuthoritative,true);
assert.equal(derived.notificationAuthoritative,true);
const authorizedAuthority=customerAuthorityDisposition(authorized);
assert.equal(authorizedAuthority.present,true);
assert.equal(authorizedAuthority.complete,true);
assert.deepEqual(authorizedAuthority.missing,[]);
assert.deepEqual(authorizedAuthority.mismatched,[]);
const withheldAuthority=customerAuthorityDisposition(withheld);
assert.equal(withheldAuthority.complete,false);
assert(withheldAuthority.missing.includes('marketComparisonAuthoritative'));
assert(withheldAuthority.missing.includes('profitRoiAuthoritative'));
const authorizedState=classifyOpportunityData(authorized,{asOf});
assert.equal(authorizedState.kind,'live');
assert.equal(authorizedState.customerVisible,true);
assert.equal(authorizedState.alertEligible,true);
const withheldState=classifyOpportunityData(withheld,{asOf});
assert.equal(withheldState.kind,'validation');
assert.equal(withheldState.customerVisible,false);
assert.equal(withheldState.alertEligible,false);
assert(withheldState.reason.startsWith('customer-authority-incomplete:'));
const forged={...authorized,id:'forged',priceHistoryObservations:verifiedHistory.slice(0,2),completedSales:verifiedSales.slice(0,2),referencePrice:999,customerProfit:500,customerRoi:400,evidenceAuthority:complete};
const forgedAuthority=customerAuthorityDisposition(forged);
assert.equal(forgedAuthority.complete,false,'claimed authority must be re-derived from customer-visible evidence');
assert(forgedAuthority.mismatched.includes('historyAuthoritative'));
assert(forgedAuthority.mismatched.includes('anomalyAuthoritative'));
assert(forgedAuthority.mismatched.includes('marketComparisonAuthoritative'));
assert(forgedAuthority.mismatched.includes('profitRoiAuthoritative'));
assert(forgedAuthority.mismatched.includes('notificationAuthoritative'));
const forgedState=classifyOpportunityData(forged,{asOf});
assert.equal(forgedState.customerVisible,false,'forged authority cannot enter the customer board');
assert.equal(forgedState.alertEligible,false,'forged authority cannot create an alert');
assert(forgedState.reason.startsWith('customer-authority-evidence-mismatch:'));
const missingEnvelope={id:'missing-envelope',dataOrigin:'live',validationState:'validated',observedAt:'2026-09-05T10:30:00.000Z',referencePrice:999,customerProfit:500,customerRoi:400,comps:{d30:899,d60:875,d90:849}};
const missingState=classifyOpportunityData(missingEnvelope,{asOf});
assert.equal(missingState.kind,'validation');
assert.equal(missingState.customerVisible,false,'validated live rows without an authority envelope must fail closed');
assert.equal(missingState.alertEligible,false);
assert.equal(missingState.reason,'customer-authority-missing');
const cachedMissing=classifyOpportunityData({...missingEnvelope,id:'cached-missing',dataOrigin:'cached'},{asOf});
assert.equal(cachedMissing.customerVisible,false,'cached customer rows must also carry an authority envelope');
assert.equal(cachedMissing.reason,'customer-authority-missing');
const demo=classifyOpportunityData({id:'demo',dataOrigin:'demo',observedAt:'2026-09-05T10:30:00.000Z'},{asOf});
assert.equal(demo.customerVisible,true,'demo rows remain usable without production authority');
assert.equal(demo.alertEligible,false);
const groups=partitionCustomerOpportunities([authorized,withheld,forged,missingEnvelope],{asOf});
assert.deepEqual(groups.live.map(x=>x.id),['authorized']);
assert.deepEqual(groups.hidden.map(x=>x.id),['withheld','forged','missing-envelope']);
console.log('customer PWA authority gate tests passed');
