const assert=require('assert');
const {rankOpportunity,buildFeed}=require('../lib/customer-feed');
const strong={health:{score:91,state:'BUY-READY',components:{freshness:96,resale:82,history:88,riskAdjustedRoi:90},watchReasons:[],blockers:[]},presentation:{badges:['Verified']},deal:{}};
const thin={health:{score:88,state:'WATCH',components:{freshness:98,resale:79,history:20,riskAdjustedRoi:86},watchReasons:['thin-price-history'],blockers:[]},presentation:{badges:['Verified']},deal:{}};
const stale={health:{score:95,state:'BLOCKED',components:{freshness:20,resale:90,history:90,riskAdjustedRoi:95},watchReasons:[],blockers:['stale-price']},presentation:{badges:['Verified']},deal:{}};
assert(rankOpportunity(strong)>=72,'strong verified buy-ready deal should rank as a top pick');
assert(rankOpportunity(thin)<=64,'thin history must cap feed priority');
assert.strictEqual(rankOpportunity(stale),0,'blocked deal must have zero feed priority');
const feed=buildFeed([thin,stale,strong]);
assert.strictEqual(feed.topPicks.length,1);
assert.strictEqual(feed.watch.length,1);
assert.strictEqual(feed.blocked.length,1);
assert.strictEqual(feed.all[0].health.state,'BUY-READY');

const base={health:{score:90,state:'BUY-READY',components:{freshness:95,resale:90,history:90,riskAdjustedRoi:88},watchReasons:[],blockers:[]},presentation:{badges:['Verified']},deal:{},evidence:{alertLevel:'instant',evidenceScore:90,confidenceBand:'high',blockers:[]}};
const fast={...base,id:'fast',strictVelocity:{capitalEfficiencyScore:92,liquidityBand:'fast'}};
const slow={...base,id:'slow',strictVelocity:{capitalEfficiencyScore:42,liquidityBand:'slow'}};
const illiquid={...base,id:'illiquid',strictVelocity:{capitalEfficiencyScore:20,liquidityBand:'illiquid'}};
assert(rankOpportunity(fast)>rankOpportunity(slow),'faster capital turns should outrank equally strong slow flips');
assert.strictEqual(rankOpportunity(illiquid),0,'illiquid resale markets must not receive feed priority');
const velocityFeed=buildFeed([slow,illiquid,fast]);
assert.strictEqual(velocityFeed.all[0].id,'fast','capital-efficient deal should lead otherwise equivalent opportunities');
assert(velocityFeed.blocked.some(x=>x.id==='illiquid'),'illiquid deal should land in blocked bucket');
console.log('customer-feed tests passed');