const assert=require('assert');
const {evaluateEvidence}=require('../lib/evidence-gate');
const strong=evaluateEvidence({history:{sampleCount:14,spanDays:45,confidence:92},anomaly:{confidence:91,phase:'fresh-drop'},resale:{confidence:88,soldCount90:18},economics:{riskAdjustedRoi:72,riskAdjustedProfit:84,downsideRoi:22,target50Headroom:18},deal:{verified:true,fresh:true}});
assert.equal(strong.alertLevel,'instant');
assert.equal(strong.alertEligible,true);
assert.equal(strong.blockers.length,0);
const thin=evaluateEvidence({history:{sampleCount:1,spanDays:1},anomaly:{confidence:95,phase:'fresh-drop'},resale:{confidence:90,soldCount90:20},economics:{riskAdjustedRoi:140,riskAdjustedProfit:120,downsideRoi:80,target50Headroom:40},deal:{verified:true,fresh:true}});
assert.equal(thin.alertLevel,'suppressed');
assert(thin.blockers.includes('insufficient-price-history'));
const weakResale=evaluateEvidence({history:{sampleCount:10,spanDays:30},anomaly:{confidence:85},resale:{confidence:30,soldCount90:1},economics:{riskAdjustedRoi:90,riskAdjustedProfit:90,downsideRoi:30},deal:{verified:true,fresh:true}});
assert.equal(weakResale.alertEligible,false);
assert(weakResale.blockers.includes('weak-resale-evidence'));
const stale=evaluateEvidence({history:{sampleCount:20,spanDays:60},anomaly:{confidence:90},resale:{confidence:90,soldCount90:20},economics:{riskAdjustedRoi:80,riskAdjustedProfit:100,downsideRoi:20},deal:{verified:true,stale:true}});
assert.equal(stale.alertLevel,'suppressed');
assert(stale.blockers.includes('stale-price'));
const standard=evaluateEvidence({history:{sampleCount:8,spanDays:21,confidence:75},anomaly:{confidence:78},resale:{confidence:76,soldCount90:7},economics:{riskAdjustedRoi:38,riskAdjustedProfit:40,downsideRoi:8,target50Headroom:-2},deal:{verified:false,fresh:true}});
assert.equal(standard.alertLevel,'standard');
assert(standard.warnings.includes('below-50pct-roi-target'));
console.log('evidence-gate tests passed');