const assert=require('assert');
const {evaluateEvidence}=require('../lib/evidence-gate');
const strong=evaluateEvidence({history:{sampleCount:14,spanDays:45,confidence:92,historyCoverageScore:96,maxGapDays:7},anomaly:{confidence:91,phase:'fresh-drop'},resale:{confidence:88,soldCount90:18},economics:{riskAdjustedRoi:72,riskAdjustedProfit:84,downsideRoi:22,target50Headroom:18},deal:{verified:true,fresh:true}});
assert.equal(strong.alertLevel,'instant');
assert.equal(strong.alertEligible,true);
assert.equal(strong.blockers.length,0);
const thin=evaluateEvidence({history:{sampleCount:1,spanDays:1},anomaly:{confidence:95,phase:'fresh-drop'},resale:{confidence:90,soldCount90:20},economics:{riskAdjustedRoi:140,riskAdjustedProfit:120,downsideRoi:80,target50Headroom:40},deal:{verified:true,fresh:true}});
assert.equal(thin.alertLevel,'suppressed');
assert(thin.blockers.includes('insufficient-price-history'));
const weakResale=evaluateEvidence({history:{sampleCount:10,spanDays:30},anomaly:{confidence:85},resale:{confidence:30,soldCount90:1},economics:{riskAdjustedRoi:90,riskAdjustedProfit:90,downsideRoi:30},deal:{verified:true,fresh:true}});
assert.equal(weakResale.alertEligible,false);
assert(weakResale.blockers.includes('weak-resale-evidence'));
const stale=evaluateEvidence({history:{sampleCount:20,spanDays:60},anomaly:{confidence:90},resale:{confidence:90,soldCount90:20},economics:{riskAdjustedRoi:80,riskAdjustedProfit:100,downsideRoi:20},deal:{verified:true,stale:true}});
assert.equal(stale.alertLevel,'suppressed');
assert(stale.blockers.includes('stale-price'));
const standard=evaluateEvidence({history:{sampleCount:8,spanDays:21,confidence:75},anomaly:{confidence:78},resale:{confidence:76,soldCount90:7},economics:{riskAdjustedRoi:38,riskAdjustedProfit:40,downsideRoi:8,target50Headroom:-2},deal:{verified:false,fresh:true}});
assert.equal(standard.alertLevel,'standard');
assert(standard.warnings.includes('below-50pct-roi-target'));
const deferred=evaluateEvidence({history:{sampleCount:16,spanDays:60,confidence:95},anomaly:{confidence:95,phase:'fresh-drop'},resale:{confidence:95,soldCount90:20},economics:{riskAdjustedRoi:80,riskAdjustedProfit:15,expectedFutureCredit:20,downsideRoi:40,confidenceAdjustedRoi:60,target50Headroom:25},deal:{verified:true,fresh:true}});
assert.equal(deferred.alertLevel,'standard','an opportunity whose profit depends on a future retailer credit must not generate an instant alert');
assert(deferred.warnings.includes('includes-deferred-retailer-credit'));
assert(deferred.warnings.includes('deferred-credit-dependent'));
assert.equal(deferred.components.deferredCreditDependent,true);
const promoUnknown=evaluateEvidence({history:{sampleCount:18,spanDays:60,confidence:95},anomaly:{confidence:95,phase:'fresh-drop'},resale:{confidence:95,soldCount90:22},economics:{riskAdjustedRoi:85,riskAdjustedProfit:90,downsideRoi:45,confidenceAdjustedRoi:70,target50Headroom:30,acquisition:{promotionStatus:'unknown',promotionReasons:['membership-eligibility-unknown'],requestedInstantDiscount:20,requestedCheckoutCredit:0,requestedFutureCredit:0}},deal:{verified:true,fresh:true}});
assert.equal(promoUnknown.alertLevel,'standard','unconfirmed member/coupon pricing must not generate an instant alert');
assert(promoUnknown.warnings.includes('promotion-eligibility-unconfirmed'));
assert.equal(promoUnknown.components.promotionUnconfirmed,true);
const promoIneligible=evaluateEvidence({history:{sampleCount:18,spanDays:60,confidence:95},anomaly:{confidence:95,phase:'fresh-drop'},resale:{confidence:95,soldCount90:22},economics:{riskAdjustedRoi:85,riskAdjustedProfit:90,downsideRoi:45,confidenceAdjustedRoi:70,target50Headroom:30,acquisition:{promotionStatus:'ineligible',promotionReasons:['promotion-expired'],requestedInstantDiscount:20}},deal:{verified:true,fresh:true}});
assert.equal(promoIneligible.alertLevel,'standard');
assert(promoIneligible.warnings.includes('promotion-not-applicable'));
const gappy=evaluateEvidence({history:{sampleCount:15,spanDays:70,confidence:91,historyCoverageScore:55,maxGapDays:38},anomaly:{confidence:93,phase:'fresh-drop'},resale:{confidence:94,soldCount90:24},economics:{riskAdjustedRoi:90,riskAdjustedProfit:110,downsideRoi:50,confidenceAdjustedRoi:70,target50Headroom:35},deal:{verified:true,fresh:true}});
assert.equal(gappy.alertLevel,'standard','gappy history must not generate instant urgency');
assert(gappy.warnings.includes('gappy-price-history'));
assert.equal(gappy.components.historyCoverageScore,55);
const brokenCoverage=evaluateEvidence({history:{sampleCount:15,spanDays:90,confidence:90,historyCoverageScore:20,maxGapDays:70},anomaly:{confidence:95},resale:{confidence:95,soldCount90:30},economics:{riskAdjustedRoi:100,riskAdjustedProfit:150,downsideRoi:60,confidenceAdjustedRoi:80},deal:{verified:true,fresh:true}});
assert.equal(brokenCoverage.alertLevel,'suppressed');
assert(brokenCoverage.blockers.includes('poor-price-history-coverage'));
console.log('evidence-gate tests passed');