'use strict';
const assert=require('assert');
const H=require('../lib/history-anomaly');
const stable=H.assessHistory({currentPrice:40,history:[120,120,118,119,120,120,118,120],asOf:'2026-09-01T18:00:00Z',evidenceQuality:.95});
assert(stable.baseline>=118&&stable.baseline<=120);
assert(stable.dropPct>60);
assert(stable.confidence>=65);
assert(stable.volatilityScore>=80);
assert.strictEqual(stable.historyCoverageScore,100);
const thin=H.assessHistory({currentPrice:40,history:[120],evidenceQuality:.95});
assert(thin.confidence<stable.confidence);
const volatile=H.assessHistory({currentPrice:40,history:[50,200,70,180,60,150],evidenceQuality:.95});
assert(volatile.volatilityScore<stable.volatilityScore);
assert(volatile.confidence<stable.confidence);
const regularObs=[0,7,14,21,28,35,42].map((d,i)=>({price:i===6?120:119+(i%2),observedAt:new Date(Date.UTC(2026,6,1+d)).toISOString()}));
const regular=H.assessHistory({currentPrice:40,observations:regularObs,asOf:'2026-08-12T00:00:00Z',evidenceQuality:.95,inferredIntervalDays:7});
assert(regular.historyCoverageScore>=90);
assert(regular.maxGapDays<=7.1);
const gappyObs=[0,1,2,3,42].map(d=>({price:120,observedAt:new Date(Date.UTC(2026,6,1+d)).toISOString()}));
const gappy=H.assessHistory({currentPrice:40,observations:gappyObs,asOf:'2026-08-12T00:00:00Z',evidenceQuality:.95,inferredIntervalDays:7});
assert(gappy.historyCoverageScore<regular.historyCoverageScore);
assert(gappy.maxGapDays>30);
assert(gappy.confidence<regular.confidence);
assert.strictEqual(gappy.label,'gappy-history');
const duplicateTimes=H.cadenceQuality([{at:1},{at:1},{at:1}],7);
assert.strictEqual(duplicateTimes.uniqueObservationCount,1);
assert.strictEqual(duplicateTimes.coverageScore,25);
const duplicateObservedAt='2026-07-01T00:00:00.000Z';
const duplicateHistory=H.assessHistory({currentPrice:40,observations:[{price:120,observedAt:duplicateObservedAt},{price:120,observedAt:duplicateObservedAt},{price:120,observedAt:duplicateObservedAt},{price:118,observedAt:'2026-07-08T00:00:00.000Z'}],asOf:'2026-07-09T00:00:00Z'});
assert.strictEqual(duplicateHistory.sampleCount,2);assert.strictEqual(duplicateHistory.uniqueObservationCount,2);assert.strictEqual(duplicateHistory.duplicateObservationCount,2);
const mixedTimeline=[0,7,14,21].flatMap((d,i)=>{const observedAt=new Date(Date.UTC(2026,7,1+d)).toISOString();return[{price:70+i,observedAt,priceBasis:'raw-shelf'},{price:160,observedAt,priceBasis:'msrp'}];});
const quarantined=H.assessHistory({currentPrice:69,observations:mixedTimeline,asOf:'2026-08-23T00:00:00Z',evidenceQuality:.95,inferredIntervalDays:7});
assert.strictEqual(H.classifyPriceObservation({priceBasis:'MSRP'}),'reference');
assert.strictEqual(H.classifyPriceObservation({priceType:'compare_at'}),'reference');
assert.strictEqual(H.classifyPriceObservation({priceBasis:'promotion-adjusted'}),'promotion');
assert.strictEqual(quarantined.sampleCount,4,'MSRP/reference rows must not enter the historical baseline');
assert(quarantined.baseline<75,'historical baseline must reflect actual observed shelf prices, not MSRP');
assert.strictEqual(quarantined.excludedReferenceObservationCount,4);
assert.strictEqual(quarantined.referenceContaminationPct,50);
assert.strictEqual(quarantined.historyIntegrityScore,50);
assert(quarantined.dropPct<10,'a $69 price must not look like a giant markdown merely because $160 MSRP rows exist');
console.log('history-anomaly tests passed');