const assert=require('assert');
const H=require('../lib/opportunity-health.js');
const strong=H.scoreOpportunity({anomalyConfidence:92,resaleConfidence:82,evidenceQuality:.94,historySamples:18,historySpanDays:70,riskAdjustedRoi:110,downsideRoi:42,marginOfSafety:38,acquisitionHeadroom:55,lifecyclePhase:'fresh-drop',freshnessScore:.98,verified:true,alertEligible:true});
assert.strictEqual(strong.state,'BUY-READY');
assert.strictEqual(strong.recommendation,'STRONG BUY');
assert(strong.score>=80,'strong verified opportunities should score highly');
assert(strong.badges.includes('Verified'));
const wait=H.scoreOpportunity({anomalyConfidence:90,resaleConfidence:38,evidenceQuality:.9,historySamples:2,historySpanDays:7,riskAdjustedRoi:80,downsideRoi:20,marginOfSafety:30,acquisitionHeadroom:35,lifecyclePhase:'fresh-drop',freshnessScore:.95,verified:true,alertEligible:true});
assert.strictEqual(wait.state,'WATCH');
assert.strictEqual(wait.recommendation,'WAIT');
assert(wait.watchReasons.includes('thin-price-history'));
assert(wait.watchReasons.includes('weak-resale-evidence'));
const blocked=H.scoreOpportunity({anomalyConfidence:95,resaleConfidence:80,evidenceQuality:.95,historySamples:20,historySpanDays:90,riskAdjustedRoi:-5,downsideRoi:-35,marginOfSafety:5,acquisitionHeadroom:-10,lifecyclePhase:'confirming-drop',freshnessScore:.2,verified:true,alertEligible:false});
assert.strictEqual(blocked.state,'BLOCKED');
assert.strictEqual(blocked.recommendation,'SKIP');
assert(blocked.blockers.includes('stale-price'));
assert(blocked.blockers.includes('negative-risk-adjusted-roi'));
assert(blocked.blockers.includes('alert-gate'));
console.log('HUNTIQ opportunity health tests passed',{strong,wait,blocked});
