const assert=require('assert');
const{assessForOpportunity,applyAlertGate}=require('../lib/pwa-marketplace-economics');
const evaluated={resale:{marketValue:100},evidenceQuality:1};
const base={price:70,feeRate:.15,shipping:15,buyerShippingRevenue:15,returnReservePct:0,paymentFixedFee:0};
const feeOnShipping=assessForOpportunity({...base,marketplaceFeeOnShipping:true},evaluated,{minNetProfit:20,minRoiPct:20});
const itemOnly=assessForOpportunity({...base,marketplaceFeeOnShipping:false},evaluated,{minNetProfit:20,minRoiPct:20});
assert.equal(feeOnShipping.grossSellerRevenue,115);
assert.equal(feeOnShipping.marketplaceFeeBase,115);
assert.equal(itemOnly.marketplaceFeeBase,100);
assert(feeOnShipping.marketplaceFee>itemOnly.marketplaceFee);
assert(feeOnShipping.netProfit<itemOnly.netProfit);
assert(feeOnShipping.totalCostBasis>feeOnShipping.acquisitionCost);
assert.equal(feeOnShipping.roiCostBasis,'all-modeled-selling-costs');
assert(feeOnShipping.warnings.includes('shipping-in-marketplace-fee-base'));
const blocked=assessForOpportunity({price:84,feeRate:.15,shipping:8,returnReservePct:3,paymentFixedFee:0},evaluated,{minNetProfit:20,minRoiPct:20});
assert.equal(blocked.eligibleForUrgentAlert,false);
const gated=applyAlertGate({alert:true,reasons:[],priority:91},blocked);
assert.equal(gated.alert,false,'PWA must not preserve an alert that fails venue-aware economics');
assert(gated.reasons.includes('marketplace-cost-floor'));
assert.equal(gated.marketplaceAlertState,'digest');
assert(gated.priority<=39);
assert.equal(gated.marketplaceEconomics.totalCostBasis,blocked.totalCostBasis);
assert.equal(gated.marketplaceEconomics.roiCostBasis,'all-modeled-selling-costs');
const warningOnly=assessForOpportunity({...base,marketplaceFeeOnShipping:true},evaluated,{minNetProfit:5,minRoiPct:5});
const downgraded=applyAlertGate({alert:true,reasons:[],priority:92},warningOnly);
assert.equal(downgraded.alert,true);
assert.equal(downgraded.marketplaceAlertState,'standard');
assert(downgraded.priority<=69,'fee-base warning should prevent instant-alert priority');
const expensiveFulfillment=assessForOpportunity({price:50,feeRate:.15,shipping:20,packagingCost:5,returnReservePct:0,paymentFixedFee:0},evaluated,{minNetProfit:5,minRoiPct:15});
assert.equal(expensiveFulfillment.netProfit,10);
assert.equal(expensiveFulfillment.totalCostBasis,90);
assert.equal(expensiveFulfillment.roiPct,11.1);
const fulfillmentGated=applyAlertGate({alert:true,reasons:[],priority:93},expensiveFulfillment);
assert.equal(fulfillmentGated.alert,false,'full-cost ROI must suppress a PWA alert that purchase-price-only ROI would have allowed');
assert(fulfillmentGated.marketplaceEconomics.fulfillmentCost>0);
console.log('pwa-marketplace-economics tests passed');