'use strict';
const assert=require('assert');
const Pwa=require('../lib/pwa-opportunity');
const asOf='2026-09-01T18:00:00.000Z';
const deal={id:'demo-1',sku:'DEMO-1',price:40,priceHistory:[120,120,118,119,120,120,118,120],comps:{d30:120,d60:116,d90:112},feeRate:.135,shipping:8,taxRate:.06,dataQuality:.95,holdingCostPerDay:.1};
const legacy={observedAt:asOf,anomaly:{confidence:90,phase:'new-drop'},resale:{estimatedDaysToSell:18}};
const out=Pwa.evaluateForPwa(deal,legacy,{asOf});
assert.equal(out.demoComparables,true);
assert.equal(out.comparables.length,9);
assert(out.comparables.every(c=>c.status==='sold'&&c.evidenceClass==='completed_sale'));
assert(out.resale.completedSaleOnly);
assert(out.resale.marketValue>0);
assert(out.economics.riskAdjustedProfit>0);
assert(out.economics.riskAdjustedRoi>0);
assert(['strong-buy','buy','watch','skip'].includes(out.recommendation));
const supplied=[{status:'sold',price:100,soldAt:'2026-08-30T18:00:00.000Z',matchScore:98,sourceConfidence:99,evidenceClass:'completed_sale'}];
const custom=Pwa.evaluateForPwa({...deal,completedSales:supplied},legacy,{asOf});
assert.equal(custom.demoComparables,false);
assert.equal(custom.comparables.length,1);
const liveWithoutSold=Pwa.evaluateForPwa({...deal,dataOrigin:'live',validationState:'validated'},legacy,{asOf});
assert.equal(liveWithoutSold.demoComparables,false);
assert.equal(liveWithoutSold.comparables.length,0,'live retailer data must never synthesize demo sold evidence');
console.log('pwa-opportunity tests passed');
