const assert=require('assert');
const qa=require('../lib/quantity-alerts');
assert.strictEqual(qa.gate({plannedUnits:0,expectedProfit:100,fulfillmentConfidence:90,recommendation:'skip-unavailable'}).blocked,true);
assert.deepStrictEqual(qa.gate({plannedUnits:2,expectedProfit:140,fulfillmentConfidence:90,recommendation:'buy-limited'}).reasons,[]);
assert.strictEqual(qa.gate({plannedUnits:1,expectedProfit:10,fulfillmentConfidence:90,recommendation:'buy-available'}).blocked,true);
const stale=qa.gate({plannedUnits:2,expectedProfit:140,fulfillmentConfidence:90,inventoryStale:true,inventoryAgeHours:24,recommendation:'buy-limited'});
assert.strictEqual(stale.blocked,true);assert(stale.reasons.includes('stale-inventory'));
const override=qa.gate({plannedUnits:2,expectedProfit:140,fulfillmentConfidence:90,inventoryStale:true,inventoryAgeHours:24,recommendation:'buy-limited'},{allowStaleInventory:true});
assert.strictEqual(override.blocked,false);
const older=qa.gate({plannedUnits:2,expectedProfit:140,fulfillmentConfidence:90,inventoryAgeHours:6,recommendation:'buy-limited'});
assert(older.priorityPenalty>=5,'aging but non-stale inventory should lower alert priority');
const freshFp=qa.fingerprint({plannedUnits:2,expectedProfit:140,fulfillmentConfidence:90,inventoryAgeHours:1,recommendation:'buy-limited'});
const staleFp=qa.fingerprint({plannedUnits:2,expectedProfit:140,fulfillmentConfidence:90,inventoryStale:true,inventoryAgeHours:24,recommendation:'buy-limited'});
assert.notEqual(freshFp,staleFp,'inventory freshness changes must alter alert state');
console.log('quantity-alert tests passed');