const assert=require('assert');
const outcome=require('../lib/resale-outcome');
const base={currentPrice:100,economics:{profit:180,roi:120,totalInvested:150},risk:{liquidation:{economics:{profit:-20}}},resale:{sold7:8,sold30:30,sold90:75,activeCount:2,resaleConfidence:90}};
const strong=outcome.assess(base);
assert(strong.sellThroughProbability>.75,'healthy demand should have strong sell-through');
assert(strong.expectedProfit>130,'healthy demand should preserve most expected profit');
assert(strong.expectedDaysToSell<10,'fast demand should produce a short capital lockup');
assert(strong.capitalTurnsPerYear>30,'fast flips should recycle capital frequently');
assert(strong.annualizedExpectedRoi>strong.expectedRoi,'fast capital turnover should lift annualized ROI');
const crowded=outcome.assess({...base,resale:{sold7:0,sold30:3,sold90:12,activeCount:25,resaleConfidence:55}});
assert(crowded.sellThroughProbability<.3,'crowded thin market should have weak sell-through');
assert(crowded.expectedProfit<strong.expectedProfit,'crowded market should reduce expected profit');
assert(crowded.expectedDaysToSell>120,'crowded demand should expose long capital lockup');
assert(crowded.capitalVelocityScore<strong.capitalVelocityScore,'crowded market should reduce capital velocity');
assert.strictEqual(crowded.status,'weak');
const improvingDemand=outcome.demandPerDay({sold7:7,sold30:15,sold90:27});
const fadingDemand=outcome.demandPerDay({sold7:1,sold30:15,sold90:60});
assert(improvingDemand>fadingDemand,'recent sold velocity should carry more weight than old demand');
const improved=outcome.fingerprint({...base,resale:{sold7:5,sold30:12,activeCount:4,resaleConfidence:80}});
const weak=outcome.fingerprint({...base,resale:{sold7:0,sold30:2,activeCount:20,resaleConfidence:50}});
assert.notStrictEqual(improved,weak,'material liquidity improvements should change fingerprint');
console.log('resale outcome tests passed',{strong,crowded});