const assert=require('assert');
const S=require('../lib/snapshot-store.js');
const row=S.normalizeSnapshot({retailer:'Home Depot',sku:'123',storeId:'18360',price:'9.03',inventory:'2',verified:true,evidenceQuality:.9,confirmationScore:85,source:'retailer',observedAt:'2026-08-30T18:00:00Z'});
assert.strictEqual(row.product,'Home Depot|123|18360');
assert.strictEqual(row.price,9.03);
assert.strictEqual(row.inventory,2);
assert.strictEqual(row.verified,true);
assert.strictEqual(row.observedAt,'2026-08-30T18:00:00.000Z');
assert.strictEqual(S.productKey({retailer:'Best Buy',sku:'ABC'}),'Best Buy|ABC|online');
assert.strictEqual(S.DB_VERSION,2);
assert.strictEqual(S.HISTORY_STORE,'price_observations');
const obs=S.normalizeObservation(row);
assert.strictEqual(obs.product,row.product);
assert.ok(obs.id.includes('Home Depot|123|18360'));
assert.ok(obs.id.includes('9.0300'));
assert.strictEqual(obs.id,S.observationId(obs));
const repeat=S.normalizeObservation(row);
assert.strictEqual(repeat.id,obs.id,'same observation should be idempotent');
const changed=S.normalizeObservation({...row,price:8.03});
assert.notStrictEqual(changed.id,obs.id,'price change must create a new ledger observation');
const later=S.normalizeObservation({...row,observedAt:'2026-08-30T19:00:00Z'});
assert.notStrictEqual(later.id,obs.id,'new polling time must be retained for history independence analysis');
console.log('HUNTIQ snapshot store tests passed',{product:row.product,price:row.price,dbVersion:S.DB_VERSION});