(function(root,factory){const api=factory(root.HuntIQAlerts,root.HuntIQStress,root.HuntIQChannels,root.HuntIQFreshness);if(typeof module==='object'&&module.exports)module.exports=factory(require('./alerts'),require('./stress'),require('./channel-economics'),require('./freshness'));else root.HuntIQAlerts=api;})(typeof globalThis!=='undefined'?globalThis:this,function(alerts,stress,channels,freshness){
'use strict';
const clamp=(n,min,max)=>Math.min(max,Math.max(min,Number(n)||0));
const defaults={minStressProfit:20,minStressRoi:15,minExitProfit:25,minExitRoi:20,minExitSafety:12,minFreshnessConfidence:45,minFreshnessAdjustedProfit:25,minFreshnessAdjustedRoi:18};
function assessStress(opportunity={},rules={}){if(!stress||typeof stress.assess!=='function')return null;return stress.assess(opportunity,rules.stressRules||{});}
function assessChannels(opportunity={}){if(!channels||typeof channels.compareChannels!=='function'||!Array.isArray(opportunity.exitChannels)||!opportunity.exitChannels.length)return null;return channels.compareChannels(opportunity,opportunity.exitChannels);}
function assessFreshness(opportunity={},rules={}){if(!freshness||typeof freshness.assess!=='function')return null;return freshness.assess(opportunity,{now:rules.now,freshHours:rules.freshHours,staleHours:rules.maxObservationAgeHours,maxFutureMinutes:rules.maxFutureMinutes});}
function stressPriority(basePriority,assessment,channelAssessment,freshnessAssessment){let p=basePriority;if(assessment&&assessment.stressEconomics){const roi=Number(assessment.stressEconomics.roi)||0;const profit=Number(assessment.stressEconomics.profit)||0;const strength=.65*clamp(roi/1.5,0,100)+.35*clamp(profit/2,0,100);p=clamp(.9*p+.1*strength,0,100);}if(channelAssessment&&channelAssessment.best){const safety=clamp((Number(channelAssessment.best.marginOfSafety)||0)*2.5,0,100);p=clamp(.90*p+.07*clamp(channelAssessment.best.score,0,100)+.03*safety,0,100);}if(freshnessAssessment){p=clamp(.88*p+.12*clamp(freshnessAssessment.confidence,0,100),0,100);}return Math.round(p);}
function shouldAlert(opportunity={},rules={}){const r={...defaults,...rules};const base=alerts.shouldAlert(opportunity,rules);const assessment=assessStress(opportunity,rules);const channelAssessment=assessChannels(opportunity);const freshnessAssessment=assessFreshness(opportunity,r);const reasons=[...base.reasons];if(assessment&&assessment.stressEconomics){if(Number(assessment.stressEconomics.profit)<r.minStressProfit&&!reasons.includes('stress-profit'))reasons.push('stress-profit');if(Number(assessment.stressEconomics.roi)<r.minStressRoi&&!reasons.includes('stress-roi'))reasons.push('stress-roi');}if(channelAssessment){if(!channelAssessment.best)reasons.push('no-exit-channel');else{if(Number(channelAssessment.best.profit)<r.minExitProfit)reasons.push('exit-profit');if(Number(channelAssessment.best.roi)<r.minExitRoi)reasons.push('exit-roi');if(Number(channelAssessment.best.marginOfSafety)<r.minExitSafety)reasons.push('exit-safety');}}let freshnessAdjustedEconomics=null;if(freshnessAssessment){freshnessAdjustedEconomics=freshness.adjustEconomics(base.confidenceAdjustedEconomics||opportunity.economics||{},freshnessAssessment);if(freshnessAssessment.status==='future'&&!reasons.includes('future-observation'))reasons.push('future-observation');if(freshnessAssessment.status==='stale'&&!reasons.includes('stale-observation'))reasons.push('stale-observation');if(Number(freshnessAssessment.confidence)<r.minFreshnessConfidence&&!reasons.includes('observation-freshness'))reasons.push('observation-freshness');if(Number(freshnessAdjustedEconomics.profit)<r.minFreshnessAdjustedProfit&&!reasons.includes('freshness-adjusted-profit'))reasons.push('freshness-adjusted-profit');if(Number(freshnessAdjustedEconomics.roi)<r.minFreshnessAdjustedRoi&&!reasons.includes('freshness-adjusted-roi'))reasons.push('freshness-adjusted-roi');}return{...base,alert:reasons.length===0,reasons,priority:stressPriority(base.priority,assessment,channelAssessment,freshnessAssessment),stressAssessment:assessment,channelAssessment,freshnessAssessment,freshnessAdjustedEconomics};}
function channelFingerprint(opportunity={}){const assessment=assessChannels(opportunity);if(!assessment||!assessment.best)return 'exit-na';const b=assessment.best;const profitBucket=Math.floor((Number(b.profit)||0)/25)*25;const roiBucket=Math.floor((Number(b.roi)||0)/20)*20;const safetyBucket=Math.floor((Number(b.marginOfSafety)||0)/10)*10;return['exit',b.name,profitBucket,roiBucket,safetyBucket,Math.round(Number(b.confidence)||0)].join(':');}
function freshnessFingerprint(opportunity={},rules={}){return freshness&&typeof freshness.fingerprint==='function'?freshness.fingerprint(opportunity,{now:rules.now,freshHours:rules.freshHours,staleHours:rules.maxObservationAgeHours,maxFutureMinutes:rules.maxFutureMinutes}):'fresh-na';}
function shouldNotify(opportunity={},previous=null,{cooldownHours=24,priorityEscalation=8,now=Date.now(),...rules}={}){const decision=shouldAlert(opportunity,{...rules,now});if(!decision.alert)return{notify:false,reason:'not-alert-eligible',decision};const fingerprint=alerts.alertFingerprint(opportunity)+'|'+channelFingerprint(opportunity)+'|'+freshnessFingerprint(opportunity,{...rules,now});if(!previous)return{notify:true,reason:'new',fingerprint,decision};const previousAt=new Date(previous.notifiedAt||0).getTime();const ageHours=Math.max(0,(Number(now)-previousAt)/36e5);if(previous.fingerprint!==fingerprint)return{notify:true,reason:'state-changed',fingerprint,decision};if(decision.priority>=Number(previous.priority||0)+priorityEscalation)return{notify:true,reason:'priority-escalation',fingerprint,decision};if(ageHours>=cooldownHours)return{notify:true,reason:'cooldown-expired',fingerprint,decision};return{notify:false,reason:'duplicate-suppressed',fingerprint,decision};}
function rankAlerts(opportunities=[],rules={}){return opportunities.map(opportunity=>({opportunity,decision:shouldAlert(opportunity,rules)})).filter(x=>x.decision.alert).sort((a,b)=>b.decision.priority-a.decision.priority||(b.opportunity.flipScore||0)-(a.opportunity.flipScore||0));}
return{...alerts,stressDefaults:defaults,assessStress,assessChannels,assessFreshness,shouldAlert,shouldNotify,rankAlerts};
});