(function(root,factory){const api=factory(root.HuntIQAlerts,root.HuntIQStress);if(typeof module==='object'&&module.exports)module.exports=factory(require('./alerts'),require('./stress'));else root.HuntIQAlerts=api;})(typeof globalThis!=='undefined'?globalThis:this,function(alerts,stress){
'use strict';
const clamp=(n,min,max)=>Math.min(max,Math.max(min,Number(n)||0));
const defaults={minStressProfit:20,minStressRoi:15};
function assessStress(opportunity={},rules={}){if(!stress||typeof stress.assess!=='function')return null;return stress.assess(opportunity,rules.stressRules||{});}
function stressPriority(basePriority,assessment){if(!assessment||!assessment.stressEconomics)return basePriority;const roi=Number(assessment.stressEconomics.roi)||0;const profit=Number(assessment.stressEconomics.profit)||0;const strength=.65*clamp(roi/1.5,0,100)+.35*clamp(profit/2,0,100);return Math.round(clamp(.9*basePriority+.1*strength,0,100));}
function shouldAlert(opportunity={},rules={}){const r={...defaults,...rules};const base=alerts.shouldAlert(opportunity,rules);const assessment=assessStress(opportunity,rules);const reasons=[...base.reasons];if(assessment&&assessment.stressEconomics){if(Number(assessment.stressEconomics.profit)<r.minStressProfit&&!reasons.includes('stress-profit'))reasons.push('stress-profit');if(Number(assessment.stressEconomics.roi)<r.minStressRoi&&!reasons.includes('stress-roi'))reasons.push('stress-roi');}return{...base,alert:reasons.length===0,reasons,priority:stressPriority(base.priority,assessment),stressAssessment:assessment};}
function shouldNotify(opportunity={},previous=null,{cooldownHours=24,priorityEscalation=8,now=Date.now(),...rules}={}){const decision=shouldAlert(opportunity,{...rules,now});if(!decision.alert)return{notify:false,reason:'not-alert-eligible',decision};const fingerprint=alerts.alertFingerprint(opportunity);if(!previous)return{notify:true,reason:'new',fingerprint,decision};const previousAt=new Date(previous.notifiedAt||0).getTime();const ageHours=Math.max(0,(Number(now)-previousAt)/36e5);if(previous.fingerprint!==fingerprint)return{notify:true,reason:'state-changed',fingerprint,decision};if(decision.priority>=Number(previous.priority||0)+priorityEscalation)return{notify:true,reason:'priority-escalation',fingerprint,decision};if(ageHours>=cooldownHours)return{notify:true,reason:'cooldown-expired',fingerprint,decision};return{notify:false,reason:'duplicate-suppressed',fingerprint,decision};}
function rankAlerts(opportunities=[],rules={}){return opportunities.map(opportunity=>({opportunity,decision:shouldAlert(opportunity,rules)})).filter(x=>x.decision.alert).sort((a,b)=>b.decision.priority-a.decision.priority||(b.opportunity.flipScore||0)-(a.opportunity.flipScore||0));}
return{...alerts,stressDefaults:defaults,assessStress,shouldAlert,shouldNotify,rankAlerts};
});