(function(root,factory){const api=factory(root.HuntIQAlerts,root.HuntIQResaleOutcome,root.HuntIQCompQuality);if(typeof module==='object'&&module.exports)module.exports=factory(require('./alert-stress'),require('./resale-outcome'),require('./comp-quality'));else root.HuntIQAlerts=api;})(typeof globalThis!=='undefined'?globalThis:this,function(alerts,outcome,compQuality){
'use strict';
const clamp=(n,min,max)=>Math.min(max,Math.max(min,Number(n)||0));
const defaults={minSellThroughPct:30,minSellThroughExpectedProfit:20,minSellThroughExpectedRoi:15,maxExpectedDaysToSell:120,minCapitalVelocityScore:25,minCompConfidence:60,minVerifiedSoldComps:2,minCompAdjustedProfit:20,minCompAdjustedRoi:15};
function assessOutcome(opportunity={},rules={}){return outcome&&typeof outcome.assess==='function'?outcome.assess(opportunity,{horizonDays:rules.sellThroughHorizonDays||30}):null;}
function assessCompQuality(opportunity={},rules={}){if(!compQuality||typeof compQuality.assess!=='function')return null;const retail=opportunity.retailProduct||opportunity.product||opportunity;const comps=opportunity.resaleComps||opportunity.comps||[];return comps.length?compQuality.assess(retail,comps,{minimumMatch:rules.minimumCompMatch||75}):null;}
function shouldAlert(opportunity={},rules={}){const r={...defaults,...rules};const base=alerts.shouldAlert(opportunity,rules);const resaleOutcome=assessOutcome(opportunity,r);const compAssessment=assessCompQuality(opportunity,r);const reasons=[...base.reasons];if(resaleOutcome){if(resaleOutcome.sellThroughPct<r.minSellThroughPct)reasons.push('sell-through');if(resaleOutcome.expectedProfit<r.minSellThroughExpectedProfit)reasons.push('sell-through-profit');if(resaleOutcome.expectedRoi<r.minSellThroughExpectedRoi)reasons.push('sell-through-roi');if(resaleOutcome.expectedDaysToSell>r.maxExpectedDaysToSell)reasons.push('capital-lockup');if(resaleOutcome.capitalVelocityScore<r.minCapitalVelocityScore)reasons.push('capital-velocity');}
let compAdjustedEconomics=null;if(compAssessment){compAdjustedEconomics=compQuality.adjustEconomics(opportunity.economics||{},compAssessment);if(compAssessment.confidence<r.minCompConfidence)reasons.push('comp-confidence');if(compAssessment.soldCount<r.minVerifiedSoldComps)reasons.push('verified-sold-comps');if(compAdjustedEconomics.compAdjustedProfit<r.minCompAdjustedProfit)reasons.push('comp-adjusted-profit');if(compAdjustedEconomics.compAdjustedRoi<r.minCompAdjustedRoi)reasons.push('comp-adjusted-roi');}
const liquidity=resaleOutcome?clamp(resaleOutcome.sellThroughPct,0,100):70;const velocity=resaleOutcome?clamp(resaleOutcome.capitalVelocityScore,0,100):70;const compScore=compAssessment?clamp(compAssessment.confidence,0,100):70;return{...base,alert:reasons.length===0,reasons,priority:Math.round(clamp(.86*base.priority+.05*liquidity+.04*velocity+.05*compScore,0,100)),resaleOutcome,compAssessment,compAdjustedEconomics};}
function shouldNotify(opportunity={},previous=null,{cooldownHours=24,priorityEscalation=8,now=Date.now(),...rules}={}){const decision=shouldAlert(opportunity,{...rules,now});if(!decision.alert)return{notify:false,reason:'not-alert-eligible',decision};const sell=outcome&&typeof outcome.fingerprint==='function'?outcome.fingerprint(opportunity,{horizonDays:rules.sellThroughHorizonDays||30}):'sell-na';const retail=opportunity.retailProduct||opportunity.product||opportunity;const comps=opportunity.resaleComps||opportunity.comps||[];const comp=compQuality&&comps.length?compQuality.fingerprint(retail,comps,{minimumMatch:rules.minimumCompMatch||75}):'comp-na';const base=alerts.shouldNotify(opportunity,null,{...rules,now});const fingerprint=(base.fingerprint||alerts.alertFingerprint(opportunity))+'|'+sell+'|'+comp;if(!previous)return{notify:true,reason:'new',fingerprint,decision};const ageHours=Math.max(0,(Number(now)-new Date(previous.notifiedAt||0).getTime())/36e5);if(previous.fingerprint!==fingerprint)return{notify:true,reason:'state-changed',fingerprint,decision};if(decision.priority>=Number(previous.priority||0)+priorityEscalation)return{notify:true,reason:'priority-escalation',fingerprint,decision};if(ageHours>=cooldownHours)return{notify:true,reason:'cooldown-expired',fingerprint,decision};return{notify:false,reason:'duplicate-suppressed',fingerprint,decision};}
function rankAlerts(opportunities=[],rules={}){return opportunities.map(opportunity=>({opportunity,decision:shouldAlert(opportunity,rules)})).filter(x=>x.decision.alert).sort((a,b)=>b.decision.priority-a.decision.priority||(b.opportunity.flipScore||0)-(a.opportunity.flipScore||0));}
return{...alerts,outcomeDefaults:defaults,assessOutcome,assessCompQuality,shouldAlert,shouldNotify,rankAlerts};
});