(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;root.HuntIQAlerts=api;})(typeof globalThis!=='undefined'?globalThis:this,function(){
'use strict';
const defaults={minFlipScore:75,minProfit:50,minRoi:40,minRiskAdjustedProfit:35,minRiskAdjustedRoi:25,minDownsideSafetyMarginPct:15,minAnomalyConfidence:65,minEvidenceQuality:.45,minConfirmationScore:35,maxObservationAgeHours:72};
const clamp=(n,min,max)=>Math.min(max,Math.max(min,Number(n)||0));
function pennyScore(opportunity={}){return clamp(opportunity.penny&&opportunity.penny.score,0,99);}
function confirmationScore(opportunity={}){return clamp(opportunity.confirmation&&opportunity.confirmation.score,0,100);}
function observationAgeHours(opportunity={},now=Date.now()){const raw=opportunity.observedAt||opportunity.latestObservedAt;if(!raw)return null;const t=new Date(raw).getTime();return Number.isFinite(t)?Math.max(0,(Number(now)-t)/36e5):null;}
function markdownUrgency(opportunity={}){const f=opportunity.penny&&opportunity.penny.forecast;if(!f||!f.forecastable)return 0;const hours=Number(f.hoursUntilNext),confidence=clamp(f.cadenceConfidence,0,100)/100;if(!Number.isFinite(hours))return 0;const proximity=hours<=0?1:clamp(1-hours/(24*7),0,1);return Math.round(100*proximity*confidence);}
function shouldAlert(opportunity={},rules={}){const r={...defaults,...rules};const econ=opportunity.economics||{};const downside=opportunity.downsideEconomics||{};const risk=opportunity.riskAdjustedEconomics||null;const anomaly=opportunity.anomaly||{};const reasons=[];const evidence=opportunity.evidenceQuality==null?1:Number(opportunity.evidenceQuality);const confirmation=opportunity.confirmation?confirmationScore(opportunity):100;if(Number(opportunity.flipScore)<r.minFlipScore)reasons.push('flip-score');if(Number(econ.profit)<r.minProfit)reasons.push('profit');if(Number(econ.roi)<r.minRoi)reasons.push('roi');if(risk&&Number(risk.profit)<r.minRiskAdjustedProfit)reasons.push('risk-adjusted-profit');if(risk&&Number(risk.roi)<r.minRiskAdjustedRoi)reasons.push('risk-adjusted-roi');if(Number.isFinite(Number(downside.safetyMarginPct))&&Number(downside.safetyMarginPct)<r.minDownsideSafetyMarginPct)reasons.push('downside-safety-margin');if(Number(anomaly.confidence)<r.minAnomalyConfidence)reasons.push('anomaly-confidence');if(evidence<r.minEvidenceQuality)reasons.push('evidence-quality');if(confirmation<r.minConfirmationScore)reasons.push('confirmation');const age=observationAgeHours(opportunity,r.now||Date.now());if(age!=null&&age>r.maxObservationAgeHours)reasons.push('stale-observation');return{alert:reasons.length===0,reasons,rules:r,priority:alertPriority(opportunity),observationAgeHours:age,confirmationScore:confirmation,markdownUrgency:markdownUrgency(opportunity)};}
function alertPriority(opportunity={}){const econ=opportunity.economics||{};const risk=opportunity.riskAdjustedEconomics||econ;const anomaly=opportunity.anomaly||{};const penny=pennyScore(opportunity);const downside=opportunity.downsideEconomics||{};const evidence=clamp((opportunity.evidenceQuality==null?1:opportunity.evidenceQuality)*100,0,100);const confirmation=opportunity.confirmation?confirmationScore(opportunity):70;const liquidity=clamp(opportunity.resale&&opportunity.resale.liquidityScore,0,100);const capital=clamp(opportunity.capitalEfficiency&&opportunity.capitalEfficiency.score,0,100);const safety=clamp((Number(downside.safetyMarginPct)||0)*1.5,0,100);const urgency=markdownUrgency(opportunity);const base=0.22*clamp(opportunity.flipScore,0,100)+0.14*clamp(anomaly.confidence,0,100)+0.09*clamp(econ.roi/3,0,100)+0.07*clamp(econ.profit/3,0,100)+0.08*clamp(risk.roi/2,0,100)+0.06*clamp(downside.roi/2,0,100)+0.06*evidence+0.07*confirmation+0.06*liquidity+0.07*capital+0.04*safety+0.04*urgency;const pennyBoost=String(opportunity.retailer||'').toLowerCase()==='home depot'?0.10*penny:0;return Math.round(clamp(base+pennyBoost,0,100));}
function alertFingerprint(opportunity={}){const p=pennyScore(opportunity);const pennyBucket=p>=80?'p80':p>=65?'p65':p>=45?'p45':'p0';const evidence=Number(opportunity.evidenceQuality==null?1:opportunity.evidenceQuality);const evidenceBucket=evidence>=.85?'e85':evidence>=.65?'e65':evidence>=.45?'e45':'e0';const c=confirmationScore(opportunity);const confirmationBucket=c>=85?'c85':c>=70?'c70':c>=55?'c55':c>=35?'c35':'c0';const risk=Number(opportunity.riskAdjustedEconomics&&opportunity.riskAdjustedEconomics.roi)||0;const riskBucket=risk>=100?'r100':risk>=60?'r60':risk>=25?'r25':'r0';const urgency=markdownUrgency(opportunity);const urgencyBucket=urgency>=70?'u70':urgency>=40?'u40':'u0';const parts=[opportunity.retailer,opportunity.sku||opportunity.id,opportunity.storeId||'online',opportunity.price,opportunity.anomaly&&opportunity.anomaly.label,evidenceBucket,confirmationBucket,riskBucket,pennyBucket,urgencyBucket].map(v=>String(v==null?'':v));return parts.join('|');}
function shouldNotify(opportunity={},previous=null,{cooldownHours=24,priorityEscalation=8,now=Date.now()}={}){const decision=shouldAlert(opportunity,{now});if(!decision.alert)return{notify:false,reason:'not-alert-eligible',decision};const fingerprint=alertFingerprint(opportunity);if(!previous)return{notify:true,reason:'new',fingerprint,decision};const previousAt=new Date(previous.notifiedAt||0).getTime();const ageHours=Math.max(0,(Number(now)-previousAt)/36e5);if(previous.fingerprint!==fingerprint)return{notify:true,reason:'state-changed',fingerprint,decision};if(decision.priority>=Number(previous.priority||0)+priorityEscalation)return{notify:true,reason:'priority-escalation',fingerprint,decision};if(ageHours>=cooldownHours)return{notify:true,reason:'cooldown-expired',fingerprint,decision};return{notify:false,reason:'duplicate-suppressed',fingerprint,decision};}
function rankAlerts(opportunities=[],rules={}){return opportunities.map(o=>({opportunity:o,decision:shouldAlert(o,rules)})).filter(x=>x.decision.alert).sort((a,b)=>b.decision.priority-a.decision.priority||(b.opportunity.flipScore||0)-(a.opportunity.flipScore||0));}
return{defaults,confirmationScore,observationAgeHours,markdownUrgency,shouldAlert,alertPriority,alertFingerprint,shouldNotify,rankAlerts};
});