(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;root.HuntIQAlerts=api;})(typeof globalThis!=='undefined'?globalThis:this,function(){
'use strict';
const defaults={minFlipScore:75,minProfit:50,minRoi:40,minAnomalyConfidence:65};
const clamp=(n,min,max)=>Math.min(max,Math.max(min,Number(n)||0));
function pennyScore(opportunity={}){return clamp(opportunity.penny&&opportunity.penny.score,0,99);}
function shouldAlert(opportunity={},rules={}){const r={...defaults,...rules};const econ=opportunity.economics||{};const anomaly=opportunity.anomaly||{};const reasons=[];if(Number(opportunity.flipScore)<r.minFlipScore)reasons.push('flip-score');if(Number(econ.profit)<r.minProfit)reasons.push('profit');if(Number(econ.roi)<r.minRoi)reasons.push('roi');if(Number(anomaly.confidence)<r.minAnomalyConfidence)reasons.push('anomaly-confidence');return{alert:reasons.length===0,reasons,rules:r,priority:alertPriority(opportunity)};}
function alertPriority(opportunity={}){const econ=opportunity.economics||{};const anomaly=opportunity.anomaly||{};const penny=pennyScore(opportunity);const downside=opportunity.downsideEconomics||{};const base=0.34*clamp(opportunity.flipScore,0,100)+0.20*clamp(anomaly.confidence,0,100)+0.15*clamp(econ.roi/3,0,100)+0.12*clamp(econ.profit/3,0,100)+0.09*clamp(downside.roi/2,0,100);const pennyBoost=String(opportunity.retailer||'').toLowerCase()==='home depot'?0.10*penny:0;return Math.round(clamp(base+pennyBoost,0,100));}
function alertFingerprint(opportunity={}){const p=pennyScore(opportunity);const pennyBucket=p>=80?'p80':p>=65?'p65':p>=45?'p45':'p0';const parts=[opportunity.retailer,opportunity.sku||opportunity.id,opportunity.storeId||'online',opportunity.price,opportunity.anomaly&&opportunity.anomaly.label,pennyBucket].map(v=>String(v==null?'':v));return parts.join('|');}
function shouldNotify(opportunity={},previous=null,{cooldownHours=24,priorityEscalation=8,now=Date.now()}={}){const decision=shouldAlert(opportunity);if(!decision.alert)return{notify:false,reason:'not-alert-eligible',decision};const fingerprint=alertFingerprint(opportunity);if(!previous)return{notify:true,reason:'new',fingerprint,decision};const previousAt=new Date(previous.notifiedAt||0).getTime();const ageHours=Math.max(0,(Number(now)-previousAt)/36e5);if(previous.fingerprint!==fingerprint)return{notify:true,reason:'state-changed',fingerprint,decision};if(decision.priority>=Number(previous.priority||0)+priorityEscalation)return{notify:true,reason:'priority-escalation',fingerprint,decision};if(ageHours>=cooldownHours)return{notify:true,reason:'cooldown-expired',fingerprint,decision};return{notify:false,reason:'duplicate-suppressed',fingerprint,decision};}
function rankAlerts(opportunities=[],rules={}){return opportunities.map(o=>({opportunity:o,decision:shouldAlert(o,rules)})).filter(x=>x.decision.alert).sort((a,b)=>b.decision.priority-a.decision.priority||(b.opportunity.flipScore||0)-(a.opportunity.flipScore||0));}
return{defaults,shouldAlert,alertPriority,alertFingerprint,shouldNotify,rankAlerts};
});