(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;root.HuntIQAlerts=api;})(typeof globalThis!=='undefined'?globalThis:this,function(){
'use strict';
const defaults={minFlipScore:75,minProfit:50,minRoi:40,minAnomalyConfidence:65,minEvidenceQuality:.45,minConfirmationScore:35,maxObservationAgeHours:72};
const clamp=(n,min,max)=>Math.min(max,Math.max(min,Number(n)||0));
function pennyScore(opportunity={}){return clamp(opportunity.penny&&opportunity.penny.score,0,99);}
function confirmationScore(opportunity={}){return clamp(opportunity.confirmation&&opportunity.confirmation.score,0,100);}
function observationAgeHours(opportunity={},now=Date.now()){const raw=opportunity.observedAt||opportunity.latestObservedAt;if(!raw)return null;const t=new Date(raw).getTime();return Number.isFinite(t)?Math.max(0,(Number(now)-t)/36e5):null;}
function shouldAlert(opportunity={},rules={}){const r={...defaults,...rules};const econ=opportunity.economics||{};const anomaly=opportunity.anomaly||{};const reasons=[];const evidence=opportunity.evidenceQuality==null?1:Number(opportunity.evidenceQuality);const confirmation=opportunity.confirmation?confirmationScore(opportunity):100;if(Number(opportunity.flipScore)<r.minFlipScore)reasons.push('flip-score');if(Number(econ.profit)<r.minProfit)reasons.push('profit');if(Number(econ.roi)<r.minRoi)reasons.push('roi');if(Number(anomaly.confidence)<r.minAnomalyConfidence)reasons.push('anomaly-confidence');if(evidence<r.minEvidenceQuality)reasons.push('evidence-quality');if(confirmation<r.minConfirmationScore)reasons.push('confirmation');const age=observationAgeHours(opportunity,r.now||Date.now());if(age!=null&&age>r.maxObservationAgeHours)reasons.push('stale-observation');return{alert:reasons.length===0,reasons,rules:r,priority:alertPriority(opportunity),observationAgeHours:age,confirmationScore:confirmation};}
function alertPriority(opportunity={}){const econ=opportunity.economics||{};const anomaly=opportunity.anomaly||{};const penny=pennyScore(opportunity);const downside=opportunity.downsideEconomics||{};const evidence=clamp((opportunity.evidenceQuality==null?1:opportunity.evidenceQuality)*100,0,100);const confirmation=opportunity.confirmation?confirmationScore(opportunity):70;const base=0.28*clamp(opportunity.flipScore,0,100)+0.17*clamp(anomaly.confidence,0,100)+0.13*clamp(econ.roi/3,0,100)+0.10*clamp(econ.profit/3,0,100)+0.08*clamp(downside.roi/2,0,100)+0.06*evidence+0.08*confirmation;const pennyBoost=String(opportunity.retailer||'').toLowerCase()==='home depot'?0.10*penny:0;return Math.round(clamp(base+pennyBoost,0,100));}
function alertFingerprint(opportunity={}){const p=pennyScore(opportunity);const pennyBucket=p>=80?'p80':p>=65?'p65':p>=45?'p45':'p0';const evidence=Number(opportunity.evidenceQuality==null?1:opportunity.evidenceQuality);const evidenceBucket=evidence>=.85?'e85':evidence>=.65?'e65':evidence>=.45?'e45':'e0';const c=confirmationScore(opportunity);const confirmationBucket=c>=85?'c85':c>=70?'c70':c>=55?'c55':c>=35?'c35':'c0';const parts=[opportunity.retailer,opportunity.sku||opportunity.id,opportunity.storeId||'online',opportunity.price,opportunity.anomaly&&opportunity.anomaly.label,evidenceBucket,confirmationBucket,pennyBucket].map(v=>String(v==null?'':v));return parts.join('|');}
function shouldNotify(opportunity={},previous=null,{cooldownHours=24,priorityEscalation=8,now=Date.now()}={}){const decision=shouldAlert(opportunity,{now});if(!decision.alert)return{notify:false,reason:'not-alert-eligible',decision};const fingerprint=alertFingerprint(opportunity);if(!previous)return{notify:true,reason:'new',fingerprint,decision};const previousAt=new Date(previous.notifiedAt||0).getTime();const ageHours=Math.max(0,(Number(now)-previousAt)/36e5);if(previous.fingerprint!==fingerprint)return{notify:true,reason:'state-changed',fingerprint,decision};if(decision.priority>=Number(previous.priority||0)+priorityEscalation)return{notify:true,reason:'priority-escalation',fingerprint,decision};if(ageHours>=cooldownHours)return{notify:true,reason:'cooldown-expired',fingerprint,decision};return{notify:false,reason:'duplicate-suppressed',fingerprint,decision};}
function rankAlerts(opportunities=[],rules={}){return opportunities.map(o=>({opportunity:o,decision:shouldAlert(o,rules)})).filter(x=>x.decision.alert).sort((a,b)=>b.decision.priority-a.decision.priority||(b.opportunity.flipScore||0)-(a.opportunity.flipScore||0));}
return{defaults,confirmationScore,observationAgeHours,shouldAlert,alertPriority,alertFingerprint,shouldNotify,rankAlerts};
});