(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;root.HuntIQBaseline=api;})(typeof globalThis!=='undefined'?globalThis:this,function(){
'use strict';
const clamp=(n,min,max)=>Math.min(max,Math.max(min,Number(n)||0));
const median=values=>{const a=values.map(Number).filter(Number.isFinite).sort((x,y)=>x-y);if(!a.length)return null;const m=Math.floor(a.length/2);return a.length%2?a[m]:(a[m-1]+a[m])/2;};
function recentWindow(observations=[],match={},options={}){const now=Number(options.now||Date.now());const hours=Math.max(1,Number(options.hours==null?24*90:options.hours)||24*90);const cutoff=now-hours*36e5;return observations.filter(o=>(!match.retailer||o.retailer===match.retailer)&&(!match.sku||o.sku===match.sku)&&(!match.storeId||o.storeId===match.storeId)).filter(o=>Number.isFinite(Number(o.price))).filter(o=>{const t=new Date(o.observedAt).getTime();return Number.isFinite(t)&&t<=now&&t>=cutoff;}).sort((a,b)=>new Date(a.observedAt)-new Date(b.observedAt));}
function independentObservations(rows=[],options={}){const spacingHours=Math.max(0,Number(options.minSpacingHours==null?6:options.minSpacingHours)||0);if(!spacingHours)return rows.slice();const spacingMs=spacingHours*36e5;const lastSeen=new Map();const kept=[];for(const row of rows){const t=new Date(row.observedAt).getTime();const key=[row.retailer||'',row.sku||'',row.storeId||'',row.sourceFamily||row.source||'',Number(row.price).toFixed(4)].join('|');const previous=lastSeen.get(key);if(previous==null||t-previous>=spacingMs){kept.push(row);lastSeen.set(key,t);}else{kept[kept.length-1]=row;lastSeen.set(key,t);}}return kept;}
function robustBaseline(observations=[],match={},options={}){const rawRows=recentWindow(observations,match,options);const rows=independentObservations(rawRows,options);const prices=rows.map(o=>Number(o.price));if(!prices.length)return{count:0,rawCount:rawRows.length,duplicateSuppressed:Math.max(0,rawRows.length),median:null,p25:null,p75:null,iqr:null,min:null,max:null,verifiedRatio:0,sourceFamilies:0,confidence:0};const sorted=[...prices].sort((a,b)=>a-b);const q=p=>{const i=(sorted.length-1)*p,lo=Math.floor(i),hi=Math.ceil(i);return sorted[lo]+(sorted[hi]-sorted[lo])*(i-lo);};const p25=q(.25),p75=q(.75),iqr=p75-p25;const verified=rows.filter(o=>o.verified).length;const sourceFamilies=new Set(rows.map(o=>o.sourceFamily||o.source).filter(Boolean)).size;const coverage=Math.min(1,rows.length/12);const sourceScore=Math.min(1,sourceFamilies/2);const verifiedScore=rows.length?verified/rows.length:0;const independenceScore=rawRows.length?rows.length/rawRows.length:0;const confidence=Math.round(100*clamp(.45*coverage+.25*sourceScore+.2*verifiedScore+.1*independenceScore,0,1));return{count:rows.length,rawCount:rawRows.length,duplicateSuppressed:Math.max(0,rawRows.length-rows.length),median:+median(prices).toFixed(2),p25:+p25.toFixed(2),p75:+p75.toFixed(2),iqr:+iqr.toFixed(2),min:Math.min(...prices),max:Math.max(...prices),verifiedRatio:+(verified/rows.length).toFixed(3),sourceFamilies,independenceRatio:+independenceScore.toFixed(3),confidence};}
function scorePriceAnomaly(currentPrice,baseline={}){const price=Number(currentPrice),med=Number(baseline.median);if(!Number.isFinite(price)||!Number.isFinite(med)||med<=0)return{score:0,confidence:0,dropPct:null,label:'Insufficient History'};const dropPct=((med-price)/med)*100;const iqr=Math.max(0,Number(baseline.iqr)||0);const relativeSpread=iqr/med;const magnitude=clamp(dropPct/70,0,1);const stability=clamp(1-relativeSpread/.5,0,1);const evidence=clamp((Number(baseline.confidence)||0)/100,0,1);const score=Math.round(100*clamp(.55*magnitude+.25*stability+.20*evidence,0,1));const confidence=Math.round(100*clamp(.6*evidence+.4*stability,0,1));const label=dropPct>=60&&score>=70?'Extreme Price Anomaly':dropPct>=35&&score>=50?'Strong Price Anomaly':dropPct>=15?'Moderate Price Anomaly':'Normal Range';return{score,confidence,dropPct:+dropPct.toFixed(1),label,baselineConfidence:Number(baseline.confidence)||0,independentObservationCount:Number(baseline.count)||0};}
return{median,recentWindow,independentObservations,robustBaseline,scorePriceAnomaly};
});