(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;root.HuntIQBaseline=api;})(typeof globalThis!=='undefined'?globalThis:this,function(){
'use strict';
const clamp=(n,min,max)=>Math.min(max,Math.max(min,Number(n)||0));
const median=values=>{const a=values.map(Number).filter(Number.isFinite).sort((x,y)=>x-y);if(!a.length)return null;const m=Math.floor(a.length/2);return a.length%2?a[m]:(a[m-1]+a[m])/2;};
const norm=v=>String(v||'').trim().toLowerCase();
const conditionOf=o=>norm(o&& (o.condition||o.itemCondition)||'new')||'new';
const priceScopeOf=o=>norm(o&&(o.priceScope||o.priceClass||o.audience)||'public')||'public';
function recentWindow(observations=[],match={},options={}){const now=Number(options.now||Date.now());const hours=Math.max(1,Number(options.hours==null?24*90:options.hours)||24*90);const cutoff=now-hours*36e5;return observations.filter(o=>(!match.retailer||o.retailer===match.retailer)&&(!match.sku||o.sku===match.sku)&&(!match.storeId||o.storeId===match.storeId)&&(!match.channel||o.channel===match.channel)&&(!match.condition||conditionOf(o)===conditionOf(match))&&(!match.priceScope||priceScopeOf(o)===priceScopeOf(match))).filter(o=>Number.isFinite(Number(o.price))).filter(o=>{const t=new Date(o.observedAt).getTime();return Number.isFinite(t)&&t<=now&&t>=cutoff;}).sort((a,b)=>new Date(a.observedAt)-new Date(b.observedAt));}
function independentObservations(rows=[],options={}){const spacingHours=Math.max(0,Number(options.minSpacingHours==null?6:options.minSpacingHours)||0);if(!spacingHours)return rows.slice();const spacingMs=spacingHours*36e5;const lastSeen=new Map();const kept=[];for(const row of rows){const t=new Date(row.observedAt).getTime();const key=[row.retailer||'',row.sku||'',row.storeId||'',row.channel||'',conditionOf(row),priceScopeOf(row),row.sourceFamily||row.source||'',Number(row.price).toFixed(4)].join('|');const previous=lastSeen.get(key);if(previous==null||t-previous>=spacingMs){kept.push(row);lastSeen.set(key,t);}else{kept[kept.length-1]=row;lastSeen.set(key,t);}}return kept;}
function excludeTrailingEpisode(rows=[],currentPrice,options={}){const price=Number(currentPrice);if(!Number.isFinite(price)||!rows.length)return{rows:rows.slice(),excluded:0};const tolerance=Math.max(0,Number(options.currentEpisodeTolerancePct==null?2:options.currentEpisodeTolerancePct)||0)/100;const maxGapHours=Math.max(1,Number(options.currentEpisodeGapHours==null?36:options.currentEpisodeGapHours)||36);const kept=rows.slice();let excluded=0,lastTime=null;for(let i=kept.length-1;i>=0;i--){const row=kept[i],p=Number(row.price),t=new Date(row.observedAt).getTime();if(!Number.isFinite(p)||!Number.isFinite(t))break;if(lastTime!=null&&(lastTime-t)>maxGapHours*36e5)break;const near=Math.abs(p-price)/Math.max(price,1)<=tolerance;if(!near)break;kept.pop();excluded++;lastTime=t;}return{rows:kept,excluded};}
function continuity(times=[],options={}){if(times.length<2)return{maxGapDays:0,continuityScore:0};let maxGap=0;for(let i=1;i<times.length;i++)maxGap=Math.max(maxGap,times[i]-times[i-1]);const maxGapDays=maxGap/864e5;const targetGapDays=Math.max(1,Number(options.targetGapDays==null?7:options.targetGapDays)||7);const spanDays=(times[times.length-1]-times[0])/864e5;const spanFactor=Math.min(1,spanDays/14);const continuityScore=clamp((1-maxGapDays/(targetGapDays*4))*.75+spanFactor*.25,0,1);return{maxGapDays:+maxGapDays.toFixed(1),continuityScore:+continuityScore.toFixed(3)};}
function robustBaseline(observations=[],match={},options={}){const rawRows=recentWindow(observations,match,options);const independent=independentObservations(rawRows,options);const episode=options.currentPrice==null?{rows:independent,excluded:0}:excludeTrailingEpisode(independent,options.currentPrice,options);const rows=episode.rows;const prices=rows.map(o=>Number(o.price));if(!prices.length)return{count:0,rawCount:rawRows.length,duplicateSuppressed:Math.max(0,rawRows.length-independent.length),currentEpisodeExcluded:episode.excluded,median:null,p25:null,p75:null,iqr:null,min:null,max:null,verifiedRatio:0,sourceFamilies:0,distinctDays:0,spanDays:0,maxGapDays:0,continuityScore:0,confidence:0};const sorted=[...prices].sort((a,b)=>a-b);const q=p=>{const i=(sorted.length-1)*p,lo=Math.floor(i),hi=Math.ceil(i);return sorted[lo]+(sorted[hi]-sorted[lo])*(i-lo);};const p25=q(.25),p75=q(.75),iqr=p75-p25;const verified=rows.filter(o=>o.verified).length;const sourceFamilies=new Set(rows.map(o=>o.sourceFamily||o.source).filter(Boolean)).size;const times=rows.map(o=>new Date(o.observedAt).getTime()).filter(Number.isFinite).sort((a,b)=>a-b);const distinctDays=new Set(times.map(t=>new Date(t).toISOString().slice(0,10))).size;const spanDays=times.length>1?(times[times.length-1]-times[0])/864e5:0;const continuityMetrics=continuity(times,options);const coverage=Math.min(1,rows.length/12);const sourceScore=Math.min(1,sourceFamilies/2);const verifiedScore=rows.length?verified/rows.length:0;const independenceScore=rawRows.length?independent.length/rawRows.length:0;const dayCoverageScore=Math.min(1,distinctDays/7);const spanScore=Math.min(1,spanDays/14);const confidence=Math.round(100*clamp(.29*coverage+.18*sourceScore+.15*verifiedScore+.09*independenceScore+.10*dayCoverageScore+.07*spanScore+.12*continuityMetrics.continuityScore,0,1));return{count:rows.length,rawCount:rawRows.length,duplicateSuppressed:Math.max(0,rawRows.length-independent.length),currentEpisodeExcluded:episode.excluded,median:+median(prices).toFixed(2),p25:+p25.toFixed(2),p75:+p75.toFixed(2),iqr:+iqr.toFixed(2),min:Math.min(...prices),max:Math.max(...prices),verifiedRatio:+(verified/rows.length).toFixed(3),sourceFamilies,independenceRatio:+independenceScore.toFixed(3),distinctDays,spanDays:+spanDays.toFixed(1),...continuityMetrics,confidence};}
function scorePriceAnomaly(currentPrice,baseline={}){const price=Number(currentPrice),med=Number(baseline.median);if(!Number.isFinite(price)||!Number.isFinite(med)||med<=0)return{score:0,confidence:0,dropPct:null,label:'Insufficient History'};const dropPct=((med-price)/med)*100;const iqr=Math.max(0,Number(baseline.iqr)||0);const relativeSpread=iqr/med;const magnitude=clamp(dropPct/70,0,1);const stability=clamp(1-relativeSpread/.5,0,1);const evidence=clamp((Number(baseline.confidence)||0)/100,0,1);const temporalCoverage=clamp(((Number(baseline.distinctDays)||0)/7)*.55+((Number(baseline.spanDays)||0)/14)*.25+(Number(baseline.continuityScore)||0)*.20,0,1);const score=Math.round(100*clamp(.52*magnitude+.23*stability+.17*evidence+.08*temporalCoverage,0,1));const confidence=Math.round(100*clamp(.50*evidence+.28*stability+.12*temporalCoverage+.10*(Number(baseline.continuityScore)||0),0,1));const label=dropPct>=60&&score>=70?'Extreme Price Anomaly':dropPct>=35&&score>=50?'Strong Price Anomaly':dropPct>=15?'Moderate Price Anomaly':'Normal Range';return{score,confidence,dropPct:+dropPct.toFixed(1),label,baselineConfidence:Number(baseline.confidence)||0,independentObservationCount:Number(baseline.count)||0,distinctDays:Number(baseline.distinctDays)||0,spanDays:Number(baseline.spanDays)||0,maxGapDays:Number(baseline.maxGapDays)||0,continuityScore:Number(baseline.continuityScore)||0,currentEpisodeExcluded:Number(baseline.currentEpisodeExcluded)||0};}
return{median,conditionOf,priceScopeOf,recentWindow,independentObservations,excludeTrailingEpisode,continuity,robustBaseline,scorePriceAnomaly};
});