(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;root.HuntIQConfirmation=api;})(typeof globalThis!=='undefined'?globalThis:this,function(){
'use strict';
const clamp=(n,min,max)=>Math.min(max,Math.max(min,Number(n)||0));
const SOURCE_FAMILIES={retailer:'retailer',"retailer-api":'retailer',"retailer-page":'retailer',"official-affiliate":'retailer',"marketplace-sold":'marketplace',"marketplace-api":'marketplace',community:'community',"community-verified":'community',unknown:'unknown',demo:'demo',"demo-current":'demo',"demo-history":'demo'};
const familyOf=source=>SOURCE_FAMILIES[String(source||'unknown').toLowerCase()]||'unknown';
function priceAgreement(items=[]){const prices=items.map(x=>Number(x.price)).filter(n=>Number.isFinite(n)&&n>=0);if(prices.length<2)return 1;const mean=prices.reduce((a,b)=>a+b,0)/prices.length;if(mean===0)return 1;const spread=(Math.max(...prices)-Math.min(...prices))/mean;return +clamp(1-spread/0.25,0,1).toFixed(3);}
function confirmationScore(items=[]){const rows=items.filter(Boolean).map(x=>({...x,family:familyOf(x.source),quality:clamp(x.quality==null?1:x.quality,0,1)}));if(!rows.length)return{score:0,label:'Unconfirmed',sourceCount:0,independentFamilies:0,priceAgreement:0,retailerConfirmed:false};const families=[...new Set(rows.map(x=>x.family).filter(x=>x!=='unknown'&&x!=='demo'))];const retailerConfirmed=rows.some(x=>x.family==='retailer'&&x.quality>=.6);const bestByFamily={};for(const row of rows)bestByFamily[row.family]=Math.max(bestByFamily[row.family]||0,row.quality);const qualityBase=Object.values(bestByFamily).sort((a,b)=>b-a).slice(0,3).reduce((s,v,i)=>s+v*(i===0?.55:i===1?.3:.15),0);const independence=clamp(families.length/3,0,1);const agreement=priceAgreement(rows);const retailerBoost=retailerConfirmed?.12:0;const score=Math.round(100*clamp(.55*qualityBase+.2*independence+.13*agreement+retailerBoost,0,1));let label='Unconfirmed';if(score>=85&&retailerConfirmed&&families.length>=2)label='Multi-Source Verified';else if(score>=70&&retailerConfirmed)label='Retailer Confirmed';else if(score>=55)label='Corroborated';else if(score>=35)label='Weak Signal';return{score,label,sourceCount:rows.length,independentFamilies:families.length,priceAgreement:agreement,retailerConfirmed};}
function confirmationMultiplier(result={}){const score=clamp(result.score,0,100);return +(0.7+0.3*(score/100)).toFixed(3);}
return{SOURCE_FAMILIES,familyOf,priceAgreement,confirmationScore,confirmationMultiplier};
});