(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;else root.HuntIQCustomerUI=api;})(typeof globalThis!=='undefined'?globalThis:this,function(){
'use strict';
function parseNumber(text){const n=Number(String(text||'').replace(/[^0-9.-]/g,''));return Number.isFinite(n)?n:null;}
function decisionFromCard(card){const score=parseNumber(card.querySelector('.flip')?.textContent)||0;const roi=parseNumber(card.querySelector('.roi')?.textContent)||0;const profit=parseNumber(card.querySelector('.profit')?.textContent)||0;const badge=(card.querySelector('.badge')?.textContent||'').toUpperCase();if(score>=90&&roi>=40&&profit>=50)return'STRONG BUY';if(score>=75&&roi>=30&&profit>0)return'BUY';if(badge.includes('ERROR')||badge.includes('EXTREME'))return'WATCH';return'WAIT';}
function enhanceCard(card){if(!card||card.dataset.customerEnhanced==='1')return;card.dataset.customerEnhanced='1';const score=card.querySelector('.flip');const decision=decisionFromCard(card);const top=card.querySelector('.deal-top');if(top){const pill=document.createElement('span');pill.className='customer-decision '+decision.toLowerCase().replace(/\s+/g,'-');pill.textContent=decision;top.appendChild(pill);}if(score){const box=score.parentElement;box?.classList.add('huntiq-score-box');const label=box?.querySelector('small');if(label)label.textContent='HUNTIQ Score';}const market=card.querySelector('.market')?.parentElement?.querySelector('small');if(market)market.textContent='Est. resale';const profit=card.querySelector('.profit')?.parentElement?.querySelector('small');if(profit)profit.textContent='Net profit';const details=card.querySelector('.details-btn');if(details)details.textContent='View Analysis';const confidence=card.querySelector('.confidence span');if(confidence){const verified=/Evidence\s+(9\d|100)%/.test(confidence.textContent||'');confidence.textContent=(verified?'✓ Verified evidence · ':'')+'Tap View Analysis for price history, resale comps, downside and risk details.';}return decision;}
function enhanceAll(rootNode=document){rootNode.querySelectorAll?.('.deal-card').forEach(enhanceCard);}
function injectStyles(){if(document.getElementById('huntiq-customer-ui-style'))return;const s=document.createElement('style');s.id='huntiq-customer-ui-style';s.textContent='.deal-card{position:relative;overflow:hidden}.customer-decision{margin-left:auto;padding:7px 10px;border-radius:999px;font-size:11px;font-weight:900;letter-spacing:.08em}.customer-decision.strong-buy,.customer-decision.buy{background:#35e0b1;color:#03110c}.customer-decision.watch,.customer-decision.wait{background:rgba(255,207,102,.12);color:#ffcf66}.huntiq-score-box{border:1px solid rgba(53,224,177,.35)!important;box-shadow:inset 0 0 24px rgba(53,224,177,.05)}.huntiq-score-box b{color:#83f7d7;font-size:24px}.details-btn{flex:1}.confidence span{line-height:1.5}.deal-card .badge{max-width:44%;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}@media(max-width:560px){.deal-card{padding:18px}.deal-card h3{margin:14px 0}.stats{gap:6px}.stats div{padding:9px}.customer-decision{position:absolute;right:16px;top:54px}}';document.head.appendChild(s);}
function boot(){injectStyles();enhanceAll();const grid=document.querySelector('#dealGrid');if(grid&&typeof MutationObserver!=='undefined')new MutationObserver(()=>enhanceAll(grid)).observe(grid,{childList:true,subtree:true});}
if(typeof document!=='undefined'){if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();}
return{parseNumber,decisionFromCard,enhanceCard,enhanceAll};
});