(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;else root.HuntIQCustomerCard=api;})(typeof globalThis!=='undefined'?globalThis:this,function(){
'use strict';
const clamp=(n,min,max)=>Math.min(max,Math.max(min,Number(n)||0));
const money=n=>Number.isFinite(Number(n))?new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(Number(n)):'n/a';
function ageMinutes(observedAt,now=Date.now()){const t=new Date(observedAt||0).getTime();return Number.isFinite(t)&&t>0?Math.max(0,Math.round((Number(now)-t)/60000)):null;}
function freshnessLabel(minutes){if(minutes==null)return'Unknown freshness';if(minutes<=15)return'Updated just now';if(minutes<60)return`Updated ${minutes}m ago`;const h=Math.round(minutes/60);if(h<24)return`Updated ${h}h ago`;return`Updated ${Math.round(h/24)}d ago`;}
function sourceLabel(o={}){const src=o.source||o.observation?.source||o.notification?.source||'unknown';const verified=o.verified??o.observation?.verified??false;return{source:String(src),verified:!!verified,label:verified?'Verified':'Unverified'};}
function locationLabel(o={}){const store=o.storeId||o.observation?.storeId||o.notification?.storeId;const zip=o.zip||o.postalCode||o.observation?.zip||o.notification?.zip;const channel=o.channel||o.observation?.channel||o.notification?.channel;return[store&&`Store ${store}`,zip&&`ZIP ${zip}`,channel&&String(channel)].filter(Boolean).join(' · ')||'Location not specified';}
function stateFrom(o={}){if(root.HuntIQExplain&&typeof root.HuntIQExplain.summary==='function')return root.HuntIQExplain.summary(o);const r=o.readiness||o.notification?.readiness;const q=o.quantityDecision||o.notification?.quantityDecision||{};if(r&&!r.ready)return{label:'WAIT',text:'WAIT',readiness:r};if(q.blocked)return{label:'SKIP',text:'SKIP',readiness:r||null};const verdict=String(o.purchaseDecision?.verdict||'WATCH').toUpperCase();return{label:verdict.includes('STRONG')?'STRONG BUY':verdict.includes('BUY')?'BUY':'WATCH',text:verdict,readiness:r||null};}
function buildCustomerCard(o={},opts={}){const s=stateFrom(o);const econ=o.economics||{};const resale=o.resale||{};const q=o.quantityEconomics||{};const source=sourceLabel(o);const minutes=ageMinutes(o.observedAt||o.observation?.observedAt||o.notification?.observedAt,opts.now||Date.now());const stale=minutes!=null&&minutes>(opts.staleAfterMinutes||120);const riskRoi=Number(o.riskAdjustedEconomics?.roi);const downsideRoi=Number(o.downsideEconomics?.roi);const reasons=(s.readiness?.reasons||[]).slice(0,3);return{state:s.label,headline:s.text,title:o.title||o.productTitle||o.sku||'Opportunity',retailer:o.retailer||o.observation?.retailer||'Retailer',price:Number(o.price??o.observation?.price),resaleValue:Number(resale.marketValue),profit:Number(econ.profit??o.profit),roi:Number(econ.roi??o.roi),riskAdjustedRoi:Number.isFinite(riskRoi)?riskRoi:null,downsideRoi:Number.isFinite(downsideRoi)?downsideRoi:null,resaleConfidence:clamp(resale.resaleConfidence,0,100),readinessScore:clamp(s.readiness?.readinessScore??s.readiness?.score,0,100),plannedUnits:Number.isFinite(Number(q.plannedUnits))?Number(q.plannedUnits):null,expectedLotProfit:Number.isFinite(Number(q.expectedLotProfit))?Number(q.expectedLotProfit):null,maxSafeBuy:Number.isFinite(Number(o.purchaseDecision?.maxBuyPrice))?Number(o.purchaseDecision.maxBuyPrice):null,source,location:locationLabel(o),freshness:{minutes,label:freshnessLabel(minutes),stale},reasons,display:{price:money(o.price??o.observation?.price),resale:money(resale.marketValue),profit:money(econ.profit??o.profit),maxSafeBuy:money(o.purchaseDecision?.maxBuyPrice)}};}
return{buildCustomerCard,ageMinutes,freshnessLabel,locationLabel,sourceLabel};
});