(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;else root.HuntIQCustomerUI=api;})(typeof globalThis!=='undefined'?globalThis:this,function(){
'use strict';
function parseNumber(text){const n=Number(String(text||'').replace(/[^0-9.-]/g,''));return Number.isFinite(n)?n:null;}
function decisionFromCard(card){const score=parseNumber(card.querySelector('.flip')?.textContent)||0;const roi=parseNumber(card.querySelector('.roi')?.textContent)||0;const profit=parseNumber(card.querySelector('.profit')?.textContent)||0;const badge=(card.querySelector('.badge')?.textContent||'').toUpperCase();if(score>=90&&roi>=40&&profit>=50)return'STRONG BUY';if(score>=75&&roi>=30&&profit>0)return'BUY';if(badge.includes('ERROR')||badge.includes('EXTREME'))return'WATCH';return'WAIT';}
function signalSummary(card){const confidence=card.querySelector('.confidence span')?.textContent||'';const drop=card.querySelector('.drop')?.textContent||'';const evidence=(confidence.match(/Evidence\s+(\d+)%/i)||[])[1];const resale=(confidence.match(/Resale band confidence\s+(\d+)%/i)||[])[1];const anomaly=(confidence.match(/Anomaly\s+(\d+)%/i)||[])[1];const maxBuy=(drop.match(/Max buy\s+([^·]+)/i)||[])[1]?.trim();const alertReady=/Alert eligible/i.test(confidence);return{evidence:evidence?Number(evidence):null,resaleConfidence:resale?Number(resale):null,anomalyConfidence:anomaly?Number(anomaly):null,maxBuy:maxBuy||null,alertReady};}
function enhanceCard(card){if(!card||card.dataset.customerEnhanced==='1')return;card.dataset.customerEnhanced='1';const score=card.querySelector('.flip');const decision=decisionFromCard(card);const top=card.querySelector('.deal-top');if(top){const pill=document.createElement('span');pill.className='customer-decision '+decision.toLowerCase().replace(/\s+/g,'-');pill.textContent=decision;top.appendChild(pill);}if(score){const box=score.parentElement;box?.classList.add('huntiq-score-box');const label=box?.querySelector('small');if(label)label.textContent='HUNTIQ Score';}const market=card.querySelector('.market')?.parentElement?.querySelector('small');if(market)market.textContent='Est. resale';const profit=card.querySelector('.profit')?.parentElement?.querySelector('small');if(profit)profit.textContent='Net profit';const details=card.querySelector('.details-btn');if(details)details.textContent='View Analysis';const signals=signalSummary(card);const confidence=card.querySelector('.confidence span');if(confidence)confidence.textContent=(signals.alertReady?'✓ Alert ready · ':'')+'Tap View Analysis for price history, resale comps, downside and risk details.';const stats=card.querySelector('.stats');if(stats&&typeof document!=='undefined'){const strip=document.createElement('div');strip.className='customer-signal-strip';const chips=[signals.alertReady?'Alert Ready':'Watching',signals.evidence!=null?`Evidence ${signals.evidence}%`:null,signals.resaleConfidence!=null?`Resale ${signals.resaleConfidence}%`:null,signals.maxBuy?`Max Buy ${signals.maxBuy}`:null].filter(Boolean);strip.innerHTML=chips.map((x,i)=>`<span${i===0&&signals.alertReady?' class="ready"':''}>${x}</span>`).join('');stats.insertAdjacentElement('afterend',strip);}return decision;}
function enhanceAll(rootNode=document){rootNode.querySelectorAll?.('.deal-card').forEach(enhanceCard);}
function injectStyles(){if(document.getElementById('huntiq-customer-ui-style'))return;const s=document.createElement('style');s.id='huntiq-customer-ui-style';s.textContent='.deal-card{position:relative;overflow:hidden}.customer-decision{margin-left:auto;padding:7px 10px;border-radius:999px;font-size:11px;font-weight:900;letter-spacing:.08em}.customer-decision.strong-buy,.customer-decision.buy{background:#35e0b1;color:#03110c}.customer-decision.watch,.customer-decision.wait{background:rgba(255,207,102,.12);color:#ffcf66}.huntiq-score-box{border:1px solid rgba(53,224,177,.35)!important;box-shadow:inset 0 0 24px rgba(53,224,177,.05)}.huntiq-score-box b{color:#83f7d7;font-size:24px}.customer-signal-strip{display:flex;flex-wrap:wrap;gap:7px;margin:10px 0 4px}.customer-signal-strip span{padding:6px 9px;border-radius:999px;background:rgba(255,255,255,.055);font-size:11px;font-weight:700;color:#b8cbc5;border:1px solid rgba(255,255,255,.07)}.customer-signal-strip span.ready{background:rgba(53,224,177,.11);border-color:rgba(53,224,177,.32);color:#83f7d7}.details-btn{flex:1}.confidence span{line-height:1.5}.deal-card .badge{max-width:44%;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}@media(max-width:560px){.deal-card{padding:18px}.deal-card h3{margin:14px 0}.stats{gap:6px}.stats div{padding:9px}.customer-decision{position:absolute;right:16px;top:54px}.customer-signal-strip{gap:5px}.customer-signal-strip span{font-size:10px;padding:5px 7px}}';document.head.appendChild(s);}
function boot(){injectStyles();enhanceAll();const grid=document.querySelector('#dealGrid');if(grid&&typeof MutationObserver!=='undefined')new MutationObserver(()=>enhanceAll(grid)).observe(grid,{childList:true,subtree:true});}
if(typeof document!=='undefined'){if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();}
return{parseNumber,decisionFromCard,signalSummary,enhanceCard,enhanceAll};
});