(function(root,factory){const api=factory(root);if(typeof module==='object'&&module.exports)module.exports=api;else root.HuntIQCustomerFeed=api;})(typeof globalThis!=='undefined'?globalThis:this,function(root){
'use strict';
const clamp=(n,min,max)=>Math.min(max,Math.max(min,Number(n)||0));
function stateWeight(state){return state==='STRONG BUY'?100:state==='BUY'?78:state==='WATCH'?54:state==='WAIT'?34:state==='SKIP'?0:20;}
function historySignal(o={}){const r=o.readiness||o.notification?.readiness||{};const count=Number(r.historySampleCount??o.historySampleCount??o.priceHistory?.length??0);const span=Number(r.historySpanDays??o.historySpanDays??0);return clamp((Math.min(count,12)/12)*60+(Math.min(span,30)/30)*40,0,100);}
function scoreOpportunity(o={},opts={}){const Card=root.HuntIQCustomerCard||(typeof require==='function'?require('./customer-card'):null);if(!Card)throw new Error('HuntIQCustomerCard required');const card=Card.buildCustomerCard(o,opts);const anomaly=clamp(o.risk?.stabilityAdjustedAnomalyConfidence??o.anomaly?.confidence??o.confidence,0,100);const resale=clamp(card.resaleConfidence,0,100);const readiness=clamp(card.readinessScore,0,100);const riskRoi=clamp(card.riskAdjustedRoi,0,250);const downsideRoi=clamp(card.downsideRoi,0,200);const history=historySignal(o);let score=stateWeight(card.state)*.28+anomaly*.18+resale*.16+readiness*.16+Math.min(riskRoi,120)/120*100*.10+Math.min(downsideRoi,80)/80*100*.06+history*.06;if(card.freshness.stale)score-=28;if(!card.source.verified)score-=12;if(card.state==='SKIP')score=0;if(card.state==='WAIT')score=Math.min(score,49);score=Math.round(clamp(score,0,100));const alertEligible=!!(o.alert?.alert??o.notification?.alert??o.alertEligible) && !card.freshness.stale && card.state!=='WAIT' && card.state!=='SKIP';return{...card,huntiqScore:score,alertEligible,signals:{anomaly,resale,readiness,riskAdjustedRoi:card.riskAdjustedRoi,downsideRoi:card.downsideRoi,history}};}
function rankFeed(items=[],opts={}){return items.map(o=>scoreOpportunity(o,opts)).sort((a,b)=>b.huntiqScore-a.huntiqScore||Number(b.expectedLotProfit||b.profit||0)-Number(a.expectedLotProfit||a.profit||0));}
function feedBuckets(items=[],opts={}){const ranked=rankFeed(items,opts);return{topPicks:ranked.filter(x=>x.state==='STRONG BUY'||x.state==='BUY'),watch:ranked.filter(x=>x.state==='WATCH'||x.state==='WAIT'),blocked:ranked.filter(x=>x.state==='SKIP'),alerts:ranked.filter(x=>x.alertEligible)};}
return{scoreOpportunity,rankFeed,feedBuckets,historySignal};
});