(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;root.HuntIQEngine=api;})(typeof globalThis!=='undefined'?globalThis:this,function(){
'use strict';
const clamp=(n,min,max)=>Math.min(max,Math.max(min,n));
const median=values=>{const a=values.filter(Number.isFinite).slice().sort((x,y)=>x-y);if(!a.length)return null;const m=Math.floor(a.length/2);return a.length%2?a[m]:(a[m-1]+a[m])/2;};
const weightedMedianMarket=({d30,d60,d90,currentAsks=[]})=>{const windows=[[Number(d30),0.5],[Number(d60),0.3],[Number(d90),0.2]].filter(([v])=>Number.isFinite(v)&&v>=0);if(!windows.length)return median((currentAsks||[]).map(Number).filter(Number.isFinite));const totalWeight=windows.reduce((s,[,w])=>s+w,0);return windows.reduce((s,[v,w])=>s+v*w,0)/totalWeight;};
function resaleSummary(input={}){const market=weightedMedianMarket(input);const sold=[input.d30,input.d60,input.d90].map(Number).filter(n=>Number.isFinite(n)&&n>=0);const soldCount=Math.max(0,Number(input.soldCount)||0);const askingMedian=median((input.currentAsks||[]).map(Number).filter(Number.isFinite));const conservativeValue=sold.length?Math.min(...sold):(market||askingMedian);const upsideValue=sold.length?Math.max(...sold):(market||askingMedian);const soldConfidence=clamp((soldCount/30)*100,0,100);const windowCoverage=sold.length/3;const resaleConfidence=Math.round(clamp(0.7*soldConfidence+20*windowCoverage+(market?10:0),0,100));return{marketValue:market,conservativeValue,upsideValue,askingMedian,soldCount,windowCoverage:+windowCoverage.toFixed(2),resaleConfidence};}
function economics({buyPrice,marketValue,feeRate=0.135,shipping=0,taxRate=0,miscCost=0}){buyPrice=Number(buyPrice);marketValue=Number(marketValue);feeRate=clamp(Number(feeRate)||0,0,0.95);shipping=Math.max(0,Number(shipping)||0);taxRate=Math.max(0,Number(taxRate)||0);miscCost=Math.max(0,Number(miscCost)||0);if(!(buyPrice>=0)||!(marketValue>=0))return{fees:0,totalCost:0,profit:0,roi:0,margin:0,breakEvenSalePrice:0};const fees=marketValue*feeRate;const purchaseTax=buyPrice*taxRate;const totalCost=buyPrice+purchaseTax+shipping+miscCost;const profit=marketValue-fees-shipping-miscCost-buyPrice-purchaseTax;const roi=totalCost>0?(profit/totalCost)*100:0;const margin=marketValue>0?(profit/marketValue)*100:0;const breakEvenSalePrice=(1-feeRate)>0?totalCost/(1-feeRate):Infinity;return{fees:+fees.toFixed(2),purchaseTax:+purchaseTax.toFixed(2),totalCost:+totalCost.toFixed(2),profit:+profit.toFixed(2),roi:+roi.toFixed(1),margin:+margin.toFixed(1),breakEvenSalePrice:Number.isFinite(breakEvenSalePrice)?+breakEvenSalePrice.toFixed(2):null};}
function anomalyScore({currentPrice,history=[],referencePrice,dataQuality=1}){currentPrice=Number(currentPrice);const hist=history.map(Number).filter(n=>Number.isFinite(n)&&n>0);const baseline=hist.length?median(hist):Number(referencePrice)||currentPrice;if(!(baseline>0)||!(currentPrice>=0))return{baseline:null,dropPct:0,zLike:0,confidence:0,label:'Insufficient Data'};const dropPct=clamp((1-currentPrice/baseline)*100,-100,100);const deviations=hist.map(v=>Math.abs(v-baseline));const mad=median(deviations)||Math.max(baseline*0.05,1);const zLike=(baseline-currentPrice)/(1.4826*mad);const historyStrength=clamp(hist.length/14,0,1);const dropSignal=clamp(dropPct/70,0,1);const outlierSignal=clamp(zLike/6,0,1);const confidence=clamp(Math.round(100*(0.45*dropSignal+0.35*outlierSignal+0.2*historyStrength)*clamp(dataQuality,0,1)),0,99);let label='Normal Price';if(confidence>=85&&dropPct>=60)label='Probable Error';else if(confidence>=65&&dropPct>=40)label='Extreme Deal';else if(dropPct>=20)label='Markdown Watch';return{baseline:+baseline.toFixed(2),dropPct:+dropPct.toFixed(1),zLike:+zLike.toFixed(2),confidence,label};}
function flipScore({anomalyConfidence=0,roi=0,soldCount=0,resaleConfidence=0}){const anomaly=clamp(anomalyConfidence,0,100);const roiStrength=clamp((roi/150)*100,0,100);const liquidity=clamp((soldCount/30)*100,0,100);const resale=clamp(resaleConfidence,0,100);return Math.round(0.38*anomaly+0.27*roiStrength+0.20*liquidity+0.15*resale);}
function evaluateOpportunity(input){const resale=resaleSummary(input.comps||{});const anomaly=anomalyScore({currentPrice:input.price,history:input.priceHistory||[],referencePrice:input.referencePrice,dataQuality:input.dataQuality==null?1:input.dataQuality});const econArgs={buyPrice:input.price,feeRate:input.feeRate,shipping:input.shipping,taxRate:input.taxRate,miscCost:input.miscCost};const econ=economics({...econArgs,marketValue:resale.marketValue||0});const downside=economics({...econArgs,marketValue:resale.conservativeValue||0});const score=flipScore({anomalyConfidence:anomaly.confidence,roi:econ.roi,soldCount:resale.soldCount,resaleConfidence:resale.resaleConfidence});return{...input,anomaly,resale,economics:econ,downsideEconomics:downside,flipScore:score};}
return{median,weightedMedianMarket,resaleSummary,economics,anomalyScore,flipScore,evaluateOpportunity};
});