(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;root.HuntIQEvidenceGate=api;})(typeof globalThis!=='undefined'?globalThis:this,function(){
'use strict';
const clamp=(n,min,max)=>Math.min(max,Math.max(min,Number(n)||0));
function evaluateEvidence({history={},anomaly={},resale={},economics={},deal={},liquidity={}}={}){
  const samples=Math.max(0,Number(history.sampleCount||history.samples||0));const spanDays=Math.max(0,Number(history.spanDays||0));const historyConfidence=clamp(history.confidence!=null?history.confidence:(samples>=12&&spanDays>=30?90:samples>=6&&spanDays>=14?72:samples>=3?50:25),0,100);const anomalyConfidence=clamp(anomaly.confidence!=null?anomaly.confidence:anomaly.score,0,100);const anomalyPhase=anomaly.phase||anomaly.lifecycle||'unknown';const resaleConfidence=clamp(resale.confidence!=null?resale.confidence:resale.resaleConfidence,0,100);const soldCount=Math.max(0,Number(resale.soldCount90||resale.soldCount30||resale.soldCount||0));const riskAdjustedRoi=Number(economics.riskAdjustedRoi)||0;const riskAdjustedProfit=Number(economics.riskAdjustedProfit)||0;const downsideRoi=economics.downsideRoi==null?riskAdjustedRoi:Number(economics.downsideRoi)||0;const confidenceAdjustedRoi=economics.confidenceAdjustedRoi==null?riskAdjustedRoi:Number(economics.confidenceAdjustedRoi)||0;const headroom=Number(economics.target50Headroom!=null?economics.target50Headroom:economics.acquisitionHeadroom)||0;const liquidityScore=liquidity.liquidityScore==null?null:clamp(liquidity.liquidityScore,0,100);const capitalEfficiencyScore=liquidity.capitalEfficiencyScore==null?null:clamp(liquidity.capitalEfficiencyScore,0,100);const liquidityBand=liquidity.liquidityBand||null;const daysToSell=liquidity.daysToSell==null?null:Math.max(0,Number(liquidity.daysToSell)||0);const fresh=deal.fresh!==false&&deal.stale!==true;const verified=Boolean(deal.verified||deal.confirmed);const blockers=[];const warnings=[];
  if(!fresh)blockers.push('stale-price');if(samples<2)blockers.push('insufficient-price-history');else if(samples<6||spanDays<14||historyConfidence<45)warnings.push('thin-price-history');if(historyConfidence<30)blockers.push('weak-history-baseline');
  if(anomalyConfidence<45)blockers.push('weak-anomaly-evidence');else if(anomalyConfidence<70)warnings.push('moderate-anomaly-evidence');if(resaleConfidence<45||soldCount<2)blockers.push('weak-resale-evidence');else if(resaleConfidence<70||soldCount<5)warnings.push('moderate-resale-evidence');if(riskAdjustedProfit<=0||riskAdjustedRoi<=0)blockers.push('negative-risk-adjusted-economics');if(downsideRoi<0)blockers.push('negative-downside-roi');if(confidenceAdjustedRoi<0)blockers.push('negative-confidence-adjusted-roi');else if(confidenceAdjustedRoi<15)warnings.push('thin-confidence-adjusted-margin');if(headroom<0)warnings.push('below-50pct-roi-target');if(anomalyPhase==='established-clearance'||anomalyPhase==='persistent-markdown')warnings.push('persistent-markdown');if(liquidityBand==='illiquid'&&(daysToSell==null||daysToSell>90||liquidityScore<30))blockers.push('illiquid-resale-market');else if(liquidityBand==='slow')warnings.push('slow-resale-velocity');if(capitalEfficiencyScore!=null&&capitalEfficiencyScore<25)warnings.push('low-capital-efficiency');
  let evidenceScore=historyConfidence*.25+anomalyConfidence*.25+resaleConfidence*.30+clamp(Math.min(riskAdjustedRoi,confidenceAdjustedRoi),0,100)*.20;if(liquidityScore!=null)evidenceScore=evidenceScore*.90+liquidityScore*.10;evidenceScore=clamp(evidenceScore,0,100);let alertLevel='digest';if(!blockers.length&&evidenceScore>=82&&riskAdjustedRoi>=50&&confidenceAdjustedRoi>=35&&verified)alertLevel='instant';else if(!blockers.length&&evidenceScore>=68&&riskAdjustedRoi>=25&&confidenceAdjustedRoi>=15)alertLevel='standard';else if(blockers.length)alertLevel='suppressed';if(alertLevel==='instant'&&(liquidityBand==='slow'||(capitalEfficiencyScore!=null&&capitalEfficiencyScore<45)))alertLevel='standard';const alertEligible=alertLevel==='instant'||alertLevel==='standard';const confidenceBand=evidenceScore>=82?'high':evidenceScore>=65?'medium':'low';return{evidenceScore:Math.round(evidenceScore),confidenceBand,alertEligible,alertLevel,blockers,warnings,components:{history:Math.round(historyConfidence),anomaly:Math.round(anomalyConfidence),resale:Math.round(resaleConfidence),riskAdjustedRoi:+riskAdjustedRoi.toFixed(1),downsideRoi:+downsideRoi.toFixed(1),confidenceAdjustedRoi:+confidenceAdjustedRoi.toFixed(1),soldCount,samples,spanDays,verified,fresh,liquidityScore:liquidityScore==null?null:Math.round(liquidityScore),capitalEfficiencyScore:capitalEfficiencyScore==null?null:Math.round(capitalEfficiencyScore),liquidityBand,daysToSell}};}
return{evaluateEvidence};
});