(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;root.HuntIQFreshness=api;})(typeof globalThis!=='undefined'?globalThis:this,function(){
'use strict';
const HOUR=36e5;
const clamp=(n,min,max)=>Math.min(max,Math.max(min,Number(n)||0));
function observedTime(opportunity={}){const raw=opportunity.observedAt||opportunity.latestObservedAt;const t=new Date(raw||0).getTime();return Number.isFinite(t)&&raw?t:null;}
function assess(opportunity={},options={}){const now=Number(options.now==null?Date.now():options.now);const freshHours=Math.max(.25,Number(options.freshHours==null?6:options.freshHours)||6);const staleHours=Math.max(freshHours,Number(options.staleHours==null?72:options.staleHours)||72);const maxFutureMinutes=Math.max(0,Number(options.maxFutureMinutes==null?5:options.maxFutureMinutes)||5);const t=observedTime(opportunity);if(t==null)return{status:'unknown',validTimestamp:false,ageHours:null,confidenceFactor:.7,confidence:70};const deltaHours=(now-t)/HOUR;if(deltaHours<-(maxFutureMinutes/60))return{status:'future',validTimestamp:false,ageHours:+deltaHours.toFixed(2),confidenceFactor:0,confidence:0};const ageHours=Math.max(0,deltaHours);let factor=1,status='fresh';if(ageHours>staleHours){factor=0;status='stale';}else if(ageHours>freshHours){const progress=(ageHours-freshHours)/Math.max(.01,staleHours-freshHours);factor=1-.65*progress;status='aging';}const confidence=Math.round(clamp(factor*100,0,100));return{status,validTimestamp:true,ageHours:+ageHours.toFixed(2),confidenceFactor:+clamp(factor,0,1).toFixed(3),confidence,freshHours,staleHours};}
function adjustEconomics(economics={},freshness={}){const factor=clamp(freshness.confidenceFactor==null?1:freshness.confidenceFactor,0,1);return{confidenceFactor:factor,profit:+((Number(economics.profit)||0)*factor).toFixed(2),roi:+((Number(economics.roi)||0)*factor).toFixed(1)};}
function fingerprint(opportunity={},options={}){const a=assess(opportunity,options);const bucket=a.status==='future'?'future':a.status==='unknown'?'unknown':a.ageHours<=1?'h1':a.ageHours<=6?'h6':a.ageHours<=24?'h24':a.ageHours<=48?'h48':a.ageHours<=72?'h72':'stale';return['fresh',bucket,a.confidence].join(':');}
return{assess,adjustEconomics,fingerprint};
});