(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;root.HuntIQFulfillment=api;})(typeof globalThis!=='undefined'?globalThis:this,function(){
'use strict';
const clamp=(n,min,max)=>Math.min(max,Math.max(min,Number(n)||0));
const SOURCE_RELIABILITY={retailer_api:1,retailer_page:.92,receipt:.97,hunter_scan:.88,hunter_report:.72,manual:.65,unknown:.6};
const SOURCE_HALF_LIFE_HOURS={retailer_api:8,retailer_page:6,receipt:36,hunter_scan:18,hunter_report:10,manual:12,unknown:8};
function temporalEvidence(opportunity={},options={}){const inventory=opportunity.inventory||{};const sourceType=String(opportunity.inventorySourceType||inventory.sourceType||opportunity.sourceType||'unknown').toLowerCase();const observedAt=opportunity.inventoryObservedAt||inventory.observedAt||opportunity.observedAt||null;const nowMs=new Date(options.now||Date.now()).getTime();const observedMs=observedAt?new Date(observedAt).getTime():NaN;const ageHours=Number.isFinite(observedMs)?Math.max(0,(nowMs-observedMs)/36e5):null;const reliability=clamp(options.sourceReliability??SOURCE_RELIABILITY[sourceType]??SOURCE_RELIABILITY.unknown,0,1);const halfLife=Math.max(.25,Number(options.halfLifeHours??SOURCE_HALF_LIFE_HOURS[sourceType]??SOURCE_HALF_LIFE_HOURS.unknown));const freshness=ageHours==null?1:Math.pow(.5,ageHours/halfLife);const temporalFactor=clamp(reliability*freshness,0,1);return{sourceType,observedAt,ageHours:ageHours==null?null:+ageHours.toFixed(2),sourceReliability:+reliability.toFixed(3),halfLifeHours:halfLife,freshness:+freshness.toFixed(3),temporalFactor:+temporalFactor.toFixed(3),stale:ageHours!=null&&freshness<.35};}
function assess(opportunity={},options={}){const inventory=opportunity.inventory||{};const quantity=Number(inventory.quantity??opportunity.inventoryQuantity);const explicit=Number(opportunity.fulfillmentConfidence??inventory.confidence);const verified=opportunity.inventoryVerified===true||inventory.verified===true;const inStock=opportunity.inStock===true||inventory.inStock===true||quantity>0;const pickup=opportunity.pickupAvailable===true||inventory.pickupAvailable===true;const sourceConfidence=Number(opportunity.evidenceQuality);let confidence=Number.isFinite(explicit)?clamp(explicit,0,100):55;if(!Number.isFinite(explicit)){if(verified)confidence+=20;if(inStock)confidence+=15;if(pickup)confidence+=5;if(Number.isFinite(sourceConfidence))confidence+=10*clamp(sourceConfidence,0,1);if(quantity===0)confidence=0;}const temporal=temporalEvidence(opportunity,options);if(temporal.observedAt)confidence*=temporal.temporalFactor;else if(options.applySourceReliabilityWithoutTimestamp===true)confidence*=temporal.sourceReliability;if(quantity===0)confidence=0;confidence=Math.round(clamp(confidence,0,100));const status=quantity===0?'unavailable':confidence>=80?'strong':confidence>=60?'moderate':'weak';return{confidence,status,verified,inStock,quantity:Number.isFinite(quantity)?quantity:null,...temporal};}
function adjustEconomics(economics={},assessment={}){const trust=clamp((Number(assessment.confidence)||0)/100,0,1);const profit=Number(economics.profit)||0;const roi=Number(economics.roi)||0;return{...economics,expectedProfit:+(profit*trust).toFixed(2),expectedRoi:+(roi*trust).toFixed(2),fulfillmentConfidence:Number(assessment.confidence)||0,inventoryAgeHours:assessment.ageHours??null,inventoryStale:assessment.stale===true};}
function fingerprint(opportunity={},options={}){const a=assess(opportunity,options);const bucket=Math.floor(a.confidence/10)*10;const ageBucket=a.ageHours==null?'na':Math.floor(a.ageHours/2)*2;return['fulfill',a.status,bucket,a.quantity==null?'na':a.quantity,a.sourceType,ageBucket,a.stale?'stale':'fresh'].join(':');}
return{SOURCE_RELIABILITY,SOURCE_HALF_LIFE_HOURS,temporalEvidence,assess,adjustEconomics,fingerprint};
});