(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;root.HuntIQHistoryQuery=api;})(typeof globalThis!=='undefined'?globalThis:this,function(){
'use strict';
const DAY=86400000;
function validTime(value){const t=new Date(value).getTime();return Number.isFinite(t)?t:null;}
function channelOf(row={}){return String(row.channel||row.priceChannel||row.fulfillment||'').trim().toLowerCase();}
function productMatch(row={},match={}){return(!match.retailer||row.retailer===match.retailer)&&(!match.sku||row.sku===match.sku)&&(!match.storeId||row.storeId===match.storeId)&&(!match.channel||channelOf(row)===String(match.channel).trim().toLowerCase());}
function windowObservations(observations=[],match={},options={}){const now=validTime(options.now)||Date.now();const days=Math.max(1,Number(options.days==null?90:options.days)||90);const cutoff=now-days*DAY;const maxRows=Math.max(1,Number(options.maxRows==null?1000:options.maxRows)||1000);return observations.filter(row=>productMatch(row,match)&&Number.isFinite(Number(row.price))).map(row=>({...row,_t:validTime(row.observedAt)})).filter(row=>row._t!=null&&row._t<=now&&row._t>=cutoff).sort((a,b)=>a._t-b._t).slice(-maxRows).map(({_t,...row})=>row);}
function coverage(observations=[],match={},options={}){const rows=windowObservations(observations,match,options);if(!rows.length)return{count:0,daysSpanned:0,distinctDays:0,verifiedRatio:0,sourceFamilies:0,priceChanges:0,channels:0};const times=rows.map(r=>validTime(r.observedAt));const distinctDays=new Set(times.map(t=>new Date(t).toISOString().slice(0,10))).size;let priceChanges=0;for(let i=1;i<rows.length;i++)if(Number(rows[i].price)!==Number(rows[i-1].price))priceChanges++;const verified=rows.filter(r=>r.verified).length;const sourceFamilies=new Set(rows.map(r=>r.sourceFamily||r.source).filter(Boolean)).size;const channels=new Set(rows.map(channelOf).filter(Boolean)).size;return{count:rows.length,daysSpanned:+((Math.max(...times)-Math.min(...times))/DAY).toFixed(1),distinctDays,verifiedRatio:+(verified/rows.length).toFixed(3),sourceFamilies,priceChanges,channels};}
function retentionCandidates(observations=[],options={}){const now=validTime(options.now)||Date.now();const retentionDays=Math.max(30,Number(options.retentionDays==null?365:options.retentionDays)||365);const cutoff=now-retentionDays*DAY;const groups=new Map();for(const row of observations){const key=[row.retailer,row.sku,row.storeId||'online',channelOf(row)||'default'].join('|');if(!groups.has(key))groups.set(key,[]);groups.get(key).push(row);}const removable=[];for(const rows of groups.values()){const sorted=rows.slice().sort((a,b)=>(validTime(a.observedAt)||0)-(validTime(b.observedAt)||0));const latest=sorted[sorted.length-1];for(const row of sorted){const t=validTime(row.observedAt);if(row!==latest&&t!=null&&t<cutoff)removable.push(row);}}return removable;}
return{channelOf,windowObservations,coverage,retentionCandidates};
});