(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;root.HuntIQHistoryAnomaly=api;})(typeof globalThis!=='undefined'?globalThis:this,function(){
'use strict';
const DAY=86400000;const FUTURE_TOLERANCE_MS=5*60*1000;const clamp=(n,min,max)=>Math.min(max,Math.max(min,Number(n)||0));
const PROMOTION_BASES=new Set(['effective','effective-unit','promotion-adjusted','basket-adjusted','multibuy-adjusted','after-rebate']);
const REFERENCE_BASES=new Set(['msrp','list','list-price','regular','regular-price','reference','reference-price','compare-at','compare-at-price','was','was-price','strike-through','strikethrough']);
function median(values=[]){const a=values.map(Number).filter(Number.isFinite).sort((x,y)=>x-y);if(!a.length)return null;const m=Math.floor(a.length/2);return a.length%2?a[m]:(a[m-1]+a[m])/2;}
function cadenceQuality(rows=[],inferredIntervalDays=7){
  if(!rows.length)return{coverageScore:100,maxGapDays:0,medianGapDays:Number(inferredIntervalDays||7),uniqueObservationCount:0};
  const times=[...new Set(rows.map(r=>r.at))].sort((a,b)=>a-b);if(times.length<2)return{coverageScore:25,maxGapDays:0,medianGapDays:Number(inferredIntervalDays||7),uniqueObservationCount:times.length};
  const gaps=times.slice(1).map((t,i)=>(t-times[i])/DAY).filter(g=>g>=0);const spanDays=(times[times.length-1]-times[0])/DAY;const medianGap=median(gaps)||Number(inferredIntervalDays||7);const maxGap=Math.max(...gaps,0);const expectedInterval=Math.max(1,Number(inferredIntervalDays||medianGap||7));const expectedCount=Math.max(2,Math.floor(spanDays/expectedInterval)+1);const density=clamp(times.length/expectedCount,0,1);const gapTolerance=Math.max(expectedInterval*3,medianGap*3,1);const gapScore=clamp(1-Math.max(0,maxGap-gapTolerance)/(gapTolerance*2),0,1);const coverageScore=Math.round(clamp((.65*density+.35*gapScore)*100,0,100));
  return{coverageScore,maxGapDays:+maxGap.toFixed(1),medianGapDays:+medianGap.toFixed(1),uniqueObservationCount:times.length};
}
function observationBasis(o={}){return String(o.priceBasis||o.priceType||o.priceKind||'raw-shelf').trim().toLowerCase().replace(/_/g,'-');}
function classifyPriceObservation(o={}){const basis=observationBasis(o);if(REFERENCE_BASES.has(basis))return'reference';if(PROMOTION_BASES.has(basis))return'promotion';return'raw';}
function isRawPriceObservation(o={}){return classifyPriceObservation(o)==='raw';}
function collapseDuplicateTimes(rows=[]){const groups=new Map();for(const row of rows){const key=row.at;if(!groups.has(key))groups.set(key,[]);groups.get(key).push(row.price);}return[...groups.entries()].map(([at,prices])=>({at:Number(at),price:median(prices)})).sort((a,b)=>a.at-b.at);}
function regimeStability(rows=[],baseline=null,madPct=0){if(!(baseline>0)||!rows.length)return{recentMedian:baseline,shiftPct:0,score:100};const recent=rows.slice(-Math.min(3,rows.length));const recentMedian=median(recent.map(r=>r.price));const shiftPct=Math.abs((Number(recentMedian)-baseline)/baseline*100);const score=clamp(100-shiftPct*2.5-Math.max(0,Number(madPct)||0)*2,5,100);return{recentMedian:+Number(recentMedian).toFixed(2),shiftPct:+shiftPct.toFixed(1),score:Math.round(score)};}
function assessHistory({currentPrice,history=[],observations=[],asOf=new Date().toISOString(),evidenceQuality=1,inferredIntervalDays=7}={}){
  const now=new Date(asOf).getTime();const supplied=Array.isArray(observations)?observations:[];const classified=supplied.map(o=>({observation:o,kind:classifyPriceObservation(o)}));const rawObservations=classified.filter(x=>x.kind==='raw').map(x=>x.observation);const excludedPromotionObservationCount=classified.filter(x=>x.kind==='promotion').length;const excludedReferenceObservationCount=classified.filter(x=>x.kind==='reference').length;const referenceContaminationPct=supplied.length?excludedReferenceObservationCount/supplied.length*100:0;const historyIntegrityScore=Math.round(clamp(100-referenceContaminationPct,0,100));
  const parsedRows=rawObservations.map(o=>({price:Number(o&&o.price),at:new Date(o&&o.observedAt).getTime()})).filter(o=>o.price>0&&Number.isFinite(o.at));const futureObservationCount=parsedRows.filter(o=>o.at>now+FUTURE_TOLERANCE_MS).length;const rawRows=parsedRows.filter(o=>o.at<=now+FUTURE_TOLERANCE_MS);const rows=collapseDuplicateTimes(rawRows);const duplicateObservationCount=Math.max(0,rawRows.length-rows.length);
  const prices=rows.length?rows.map(r=>r.price):(history||[]).map(Number).filter(n=>n>0&&Number.isFinite(n));const sampleCount=prices.length;const baseline=median(prices);currentPrice=Number(currentPrice);const cadence=rows.length?cadenceQuality(rows,inferredIntervalDays):{coverageScore:100,maxGapDays:Math.max(0,Number(inferredIntervalDays||7)),medianGapDays:Math.max(0,Number(inferredIntervalDays||7)),uniqueObservationCount:sampleCount};
  if(!(baseline>0)||!(currentPrice>=0))return{sampleCount,spanDays:0,baseline:null,madPct:null,volatilityScore:0,regimeStabilityScore:0,regimeShiftPct:0,recentMedian:null,freshnessScore:0,historyCoverageScore:cadence.coverageScore,maxGapDays:cadence.maxGapDays,medianGapDays:cadence.medianGapDays,uniqueObservationCount:cadence.uniqueObservationCount,excludedPromotionObservationCount,excludedReferenceObservationCount,referenceContaminationPct:+referenceContaminationPct.toFixed(1),historyIntegrityScore,duplicateObservationCount,futureObservationCount,dropPct:0,zLike:0,confidence:0,label:'insufficient-history'};
  const mad=median(prices.map(v=>Math.abs(v-baseline)))||Math.max(1,baseline*.01);const madPct=mad/baseline*100;const dropPct=clamp((1-currentPrice/baseline)*100,-100,100);const zLike=(baseline-currentPrice)/(1.4826*mad);
  const spanDays=rows.length>1?(Math.max(...rows.map(r=>r.at))-Math.min(...rows.map(r=>r.at)))/DAY:Math.max(0,(sampleCount-1)*Number(inferredIntervalDays||7));
  const newest=rows.length?Math.min(now,Math.max(...rows.map(r=>r.at))):now;const ageDays=Math.max(0,(now-newest)/DAY);const freshnessScore=clamp(100-ageDays*6,0,100);const volatilityScore=clamp(100-madPct*7,10,100);const regime=regimeStability(rows,baseline,madPct);const sampleScore=clamp(sampleCount/12*100,0,100);const spanScore=clamp(spanDays/42*100,0,100);const dropSignal=clamp(dropPct/65*100,0,100);const outlierSignal=clamp(zLike/6*100,0,100);const evidence=clamp(evidenceQuality,0,1);const historyCoverageScore=clamp(cadence.coverageScore,0,100);
  const raw=.26*dropSignal+.22*outlierSignal+.14*sampleScore+.10*spanScore+.08*freshnessScore+.05*volatilityScore+.10*historyCoverageScore+.05*regime.score;const integrityFactor=.7+.3*(historyIntegrityScore/100);const confidence=Math.round(clamp(raw*evidence*integrityFactor,0,99));
  let label='normal';if(regime.score<40&&sampleCount>=6)label='unstable-price-regime';else if(historyCoverageScore<70&&sampleCount>=3)label='gappy-history';else if(confidence>=82&&dropPct>=55)label='high-confidence-anomaly';else if(confidence>=65&&dropPct>=35)label='strong-markdown';else if(dropPct>=20)label='markdown-watch';else if(sampleCount<3)label='thin-history';
  return{sampleCount,spanDays:+spanDays.toFixed(1),baseline:+baseline.toFixed(2),madPct:+madPct.toFixed(2),volatilityScore:Math.round(volatilityScore),regimeStabilityScore:regime.score,regimeShiftPct:regime.shiftPct,recentMedian:regime.recentMedian,freshnessScore:Math.round(freshnessScore),historyCoverageScore:Math.round(historyCoverageScore),maxGapDays:cadence.maxGapDays,medianGapDays:cadence.medianGapDays,uniqueObservationCount:cadence.uniqueObservationCount,excludedPromotionObservationCount,excludedReferenceObservationCount,referenceContaminationPct:+referenceContaminationPct.toFixed(1),historyIntegrityScore,duplicateObservationCount,futureObservationCount,dropPct:+dropPct.toFixed(1),zLike:+zLike.toFixed(2),confidence,label};
}
return{median,cadenceQuality,observationBasis,classifyPriceObservation,isRawPriceObservation,collapseDuplicateTimes,regimeStability,assessHistory};
});