(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;root.HuntIQHistory=api;})(typeof globalThis!=='undefined'?globalThis:this,function(){
'use strict';
const DB_NAME='huntiq';const DB_VERSION=3;const STORE='price_history';const EVENT_STORE='markdown_events';
const normalizeObservation=(o={})=>({retailer:String(o.retailer||'').trim(),sku:String(o.sku||o.id||'').trim(),storeId:String(o.storeId||'online'),price:Number(o.price),observedAt:o.observedAt||new Date().toISOString(),inventory:o.inventory==null?null:Number(o.inventory),source:o.source||'unknown'});
const productKey=o=>`${o.retailer}|${o.sku}|${o.storeId}`;
const observationKey=o=>`${productKey(o)}|${o.observedAt}`;
const normalizeMarkdownEvent=(e={})=>({retailer:String(e.retailer||'').trim(),sku:String(e.sku||e.id||'').trim(),storeId:String(e.storeId||'online'),fromPrice:Number(e.fromPrice),toPrice:Number(e.toPrice),dropPct:Number(e.dropPct),observedAt:e.observedAt||new Date().toISOString(),inventory:e.inventory==null?null:Number(e.inventory),source:e.source||'derived'});
const markdownEventKey=e=>`${productKey(e)}|${e.observedAt}|${Number(e.toPrice).toFixed(2)}`;
function series(observations=[],match={}){return observations.filter(o=>(!match.retailer||o.retailer===match.retailer)&&(!match.sku||o.sku===match.sku)&&(!match.storeId||o.storeId===match.storeId)).filter(o=>Number.isFinite(Number(o.price))).sort((a,b)=>new Date(a.observedAt)-new Date(b.observedAt));}
function priceHistory(observations=[],match={}){return series(observations,match).map(o=>Number(o.price));}
function latest(observations=[],match={}){const s=series(observations,match);return s.length?s[s.length-1]:null;}
function summarize(observations=[],match={}){const s=series(observations,match);if(!s.length)return{count:0,first:null,latest:null,min:null,max:null};const prices=s.map(o=>Number(o.price));return{count:s.length,first:s[0],latest:s[s.length-1],min:Math.min(...prices),max:Math.max(...prices)};}
function openDb(){return new Promise((resolve,reject)=>{if(typeof indexedDB==='undefined')return reject(new Error('IndexedDB unavailable'));const req=indexedDB.open(DB_NAME,DB_VERSION);req.onupgradeneeded=()=>{const db=req.result;let store;if(!db.objectStoreNames.contains(STORE)){store=db.createObjectStore(STORE,{keyPath:'key'});}else{store=req.transaction.objectStore(STORE);}if(!store.indexNames.contains('product'))store.createIndex('product','product',{unique:false});if(!store.indexNames.contains('observedAt'))store.createIndex('observedAt','observedAt',{unique:false});if(!store.indexNames.contains('retailer'))store.createIndex('retailer','retailer',{unique:false});let events;if(!db.objectStoreNames.contains(EVENT_STORE)){events=db.createObjectStore(EVENT_STORE,{keyPath:'key'});}else{events=req.transaction.objectStore(EVENT_STORE);}if(!events.indexNames.contains('product'))events.createIndex('product','product',{unique:false});if(!events.indexNames.contains('retailer'))events.createIndex('retailer','retailer',{unique:false});if(!events.indexNames.contains('observedAt'))events.createIndex('observedAt','observedAt',{unique:false});};req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error);});}
async function saveObservation(input){const o=normalizeObservation(input);if(!o.retailer||!o.sku||!Number.isFinite(o.price))throw new Error('retailer, sku and numeric price are required');const row={...o,key:observationKey(o),product:productKey(o)};const db=await openDb();await new Promise((resolve,reject)=>{const tx=db.transaction(STORE,'readwrite');tx.objectStore(STORE).put(row);tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error);});db.close();return row;}
async function saveMarkdownEvent(input){const e=normalizeMarkdownEvent(input);if(!e.retailer||!e.sku||!Number.isFinite(e.fromPrice)||!Number.isFinite(e.toPrice)||e.toPrice>=e.fromPrice)throw new Error('valid retailer, sku and downward price event are required');const row={...e,key:markdownEventKey(e),product:productKey(e)};const db=await openDb();await new Promise((resolve,reject)=>{const tx=db.transaction(EVENT_STORE,'readwrite');tx.objectStore(EVENT_STORE).put(row);tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error);});db.close();return row;}
async function getHistory(match={}){const db=await openDb();const rows=await new Promise((resolve,reject)=>{const tx=db.transaction(STORE,'readonly');const store=tx.objectStore(STORE);let req;if(match.retailer&&match.sku&&match.storeId){req=store.index('product').getAll(productKey(match));}else if(match.retailer){req=store.index('retailer').getAll(match.retailer);}else{req=store.getAll();}req.onsuccess=()=>resolve(req.result||[]);req.onerror=()=>reject(req.error);});db.close();return series(rows,match);}
async function getMarkdownEvents(match={}){const db=await openDb();const rows=await new Promise((resolve,reject)=>{const tx=db.transaction(EVENT_STORE,'readonly');const store=tx.objectStore(EVENT_STORE);let req;if(match.retailer&&match.sku&&match.storeId){req=store.index('product').getAll(productKey(match));}else if(match.retailer){req=store.index('retailer').getAll(match.retailer);}else{req=store.getAll();}req.onsuccess=()=>resolve(req.result||[]);req.onerror=()=>reject(req.error);});db.close();return rows.filter(e=>(!match.retailer||e.retailer===match.retailer)&&(!match.sku||e.sku===match.sku)&&(!match.storeId||e.storeId===match.storeId)).sort((a,b)=>new Date(a.observedAt)-new Date(b.observedAt));}
async function getRecentHistory(match={},limit=30){const rows=await getHistory(match);const n=Math.max(1,Number(limit)||30);return rows.slice(-n);}
return{normalizeObservation,normalizeMarkdownEvent,productKey,observationKey,markdownEventKey,series,priceHistory,latest,summarize,saveObservation,saveMarkdownEvent,getHistory,getMarkdownEvents,getRecentHistory};
});