(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;root.HuntIQMarkdown=api;})(typeof globalThis!=='undefined'?globalThis:this,function(){
'use strict';
const clamp=(n,min,max)=>Math.min(max,Math.max(min,n));
const median=values=>{const a=values.filter(Number.isFinite).slice().sort((x,y)=>x-y);if(!a.length)return null;const m=Math.floor(a.length/2);return a.length%2?a[m]:(a[m-1]+a[m])/2;};
const hoursBetween=(a,b)=>Math.max(0,(new Date(b)-new Date(a))/36e5);
function detectMarkdownEvents(observations=[]){const rows=observations.filter(o=>Number.isFinite(Number(o.price))).slice().sort((a,b)=>new Date(a.observedAt)-new Date(b.observedAt));const events=[];for(let i=1;i<rows.length;i++){const prev=rows[i-1],cur=rows[i];const from=Number(prev.price),to=Number(cur.price);if(!(from>0)||!(to>=0)||to>=from)continue;const dropPct=(1-to/from)*100;events.push({fromPrice:+from.toFixed(2),toPrice:+to.toFixed(2),dropPct:+dropPct.toFixed(1),observedAt:cur.observedAt,hoursSincePrior:+hoursBetween(prev.observedAt,cur.observedAt).toFixed(1),inventory:cur.inventory==null?null:Number(cur.inventory)});}return events;}
function markdownVelocity(observations=[]){const events=detectMarkdownEvents(observations);if(!events.length)return{events:0,totalDropPct:0,avgDropPct:0,avgHoursBetweenDrops:null,velocityScore:0};const totalDropPct=events.reduce((s,e)=>s+e.dropPct,0);const intervals=events.slice(1).map((e,i)=>hoursBetween(events[i].observedAt,e.observedAt)).filter(Number.isFinite);const avgHours=intervals.length?intervals.reduce((s,v)=>s+v,0)/intervals.length:null;const frequency=clamp(events.length/4,0,1);const depth=clamp((totalDropPct/events.length)/50,0,1);const recency=avgHours==null?0.35:clamp(1-(avgHours/(24*21)),0,1);return{events:events.length,totalDropPct:+totalDropPct.toFixed(1),avgDropPct:+(totalDropPct/events.length).toFixed(1),avgHoursBetweenDrops:avgHours==null?null:+avgHours.toFixed(1),velocityScore:Math.round(100*(0.35*frequency+0.4*depth+0.25*recency))};}
function inventorySignal(observations=[]){const rows=observations.filter(o=>Number.isFinite(Number(o.inventory))).slice().sort((a,b)=>new Date(a.observedAt)-new Date(b.observedAt));if(rows.length<2)return{start:null,current:null,change:null,signal:0};const start=Number(rows[0].inventory),current=Number(rows[rows.length-1].inventory),change=current-start;const soldThrough=start>0?clamp((start-current)/start,0,1):0;return{start,current,change,signal:Math.round(soldThrough*100)};}
function forecastNextMarkdown(observations=[],now=new Date()){
 const events=detectMarkdownEvents(observations);
 if(events.length<2)return{forecastable:false,events:events.length,medianIntervalHours:null,hoursUntilNext:null,expectedAt:null,cadenceConfidence:0};
 const intervals=[];for(let i=1;i<events.length;i++){const h=hoursBetween(events[i-1].observedAt,events[i].observedAt);if(Number.isFinite(h)&&h>0)intervals.push(h);}if(!intervals.length)return{forecastable:false,events:events.length,medianIntervalHours:null,hoursUntilNext:null,expectedAt:null,cadenceConfidence:0};
 const med=median(intervals);const deviations=intervals.map(v=>Math.abs(v-med));const mad=median(deviations)||0;const consistency=med>0?clamp(1-(mad/med),0,1):0;const sampleStrength=clamp(intervals.length/4,0,1);const cadenceConfidence=Math.round(100*(.65*consistency+.35*sampleStrength));const latest=new Date(events[events.length-1].observedAt);const expected=new Date(latest.getTime()+med*36e5);const hoursUntil=(expected-new Date(now))/36e5;return{forecastable:true,events:events.length,medianIntervalHours:+med.toFixed(1),hoursUntilNext:+hoursUntil.toFixed(1),expectedAt:expected.toISOString(),cadenceConfidence};
}
function pennyProbability({observations=[],currentPrice,referencePrice,anomalyConfidence=0,dataQuality=1}){const rows=observations.filter(o=>Number.isFinite(Number(o.price))).slice().sort((a,b)=>new Date(a.observedAt)-new Date(b.observedAt));const latestPrice=Number.isFinite(Number(currentPrice))?Number(currentPrice):(rows.length?Number(rows[rows.length-1].price):NaN);const ref=Number(referencePrice)||Math.max(...rows.map(o=>Number(o.price)).filter(Number.isFinite),latestPrice||0);const markdown=markdownVelocity(rows);const inv=inventorySignal(rows);const forecast=forecastNextMarkdown(rows);const priceDepth=ref>0&&Number.isFinite(latestPrice)?clamp((1-latestPrice/ref)/0.9,0,1):0;const subDollar=latestPrice>0&&latestPrice<=1?1:latestPrice>0&&latestPrice<=5?0.75:latestPrice>0&&latestPrice<=20?0.35:0;const anomaly=clamp(Number(anomalyConfidence)/100,0,1);const velocity=markdown.velocityScore/100;const quality=clamp(Number(dataQuality),0,1);const cadence=forecast.forecastable?forecast.cadenceConfidence/100:0;const score=clamp(Math.round(100*(0.3*priceDepth+0.22*velocity+0.18*anomaly+0.12*subDollar+0.08*(inv.signal/100)+0.06*quality+0.04*cadence)),0,99);let label='Low';if(score>=80)label='Very High';else if(score>=65)label='High';else if(score>=45)label='Watch';return{score,label,latestPrice:Number.isFinite(latestPrice)?latestPrice:null,referencePrice:ref||null,markdown,inventory:inv,forecast};}
return{detectMarkdownEvents,markdownVelocity,inventorySignal,forecastNextMarkdown,pennyProbability};
});