(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;root.HuntIQOpportunityHealth=api;})(typeof globalThis!=='undefined'?globalThis:this,function(){
'use strict';
const clamp=(n,min,max)=>Math.min(max,Math.max(min,Number(n)||0));
function scoreOpportunity({anomalyConfidence=0,resaleConfidence=0,evidenceQuality=0,historySamples=0,historySpanDays=0,riskAdjustedRoi=0,downsideRoi=0,marginOfSafety=0,acquisitionHeadroom=0,lifecyclePhase='normal',freshnessScore=1,verified=false,alertEligible=true}={}){
  const evidencePct=evidenceQuality<=1?evidenceQuality*100:evidenceQuality;
  const freshnessPct=freshnessScore<=1?freshnessScore*100:freshnessScore;
  const historyDepth=clamp(historySamples/12*100,0,100);
  const historySpan=clamp(historySpanDays/60*100,0,100);
  const historyScore=.6*historyDepth+.4*historySpan;
  const roiScore=clamp(riskAdjustedRoi/1.5,0,100);
  const downsideScore=clamp((downsideRoi+20)/1.2,0,100);
  const safetyScore=clamp(marginOfSafety*2,0,100);
  const headroomScore=clamp(acquisitionHeadroom>0?50+Math.min(50,acquisitionHeadroom):0,0,100);
  let lifecycleFactor=1;
  if(lifecyclePhase==='established-clearance')lifecycleFactor=.92;
  else if(lifecyclePhase==='persistent-markdown')lifecycleFactor=.96;
  else if(lifecyclePhase==='fresh-drop')lifecycleFactor=1.03;
  let score=(.20*clamp(anomalyConfidence,0,100)+.18*clamp(resaleConfidence,0,100)+.14*clamp(evidencePct,0,100)+.12*historyScore+.18*roiScore+.08*downsideScore+.05*safetyScore+.05*headroomScore)*lifecycleFactor;
  if(verified)score+=3;
  score=Math.round(clamp(score,0,99));
  const blockers=[],watch=[];
  if(freshnessPct<45)blockers.push('stale-price');
  if(riskAdjustedRoi<0)blockers.push('negative-risk-adjusted-roi');
  if(downsideRoi<-20)blockers.push('downside-loss');
  if(!alertEligible)blockers.push('alert-gate');
  if(historySamples<4)watch.push('thin-price-history');
  if(historySpanDays<14)watch.push('short-history-span');
  if(resaleConfidence<45)watch.push('weak-resale-evidence');
  if(evidencePct<55)watch.push('weak-source-evidence');
  if(riskAdjustedRoi<35)watch.push('low-risk-adjusted-roi');
  let state='BUY-READY';
  if(blockers.length)state='BLOCKED'; else if(watch.length)state='WATCH';
  let recommendation='STRONG BUY';
  if(state==='BLOCKED')recommendation='SKIP';
  else if(state==='WATCH')recommendation='WAIT';
  else if(score<72)recommendation='BUY';
  const badges=[];
  if(verified)badges.push('Verified');
  if(resaleConfidence>=70)badges.push('Strong Resale');
  if(historySamples>=12&&historySpanDays>=30)badges.push('Deep History');
  if(riskAdjustedRoi>=75)badges.push('High ROI');
  if(lifecyclePhase==='fresh-drop')badges.push('Fresh Drop');
  return{score,state,recommendation,blockers,watchReasons:watch,badges,components:{anomaly:Math.round(clamp(anomalyConfidence,0,100)),resale:Math.round(clamp(resaleConfidence,0,100)),evidence:Math.round(clamp(evidencePct,0,100)),history:Math.round(historyScore),riskAdjustedRoi:Math.round(roiScore),downside:Math.round(downsideScore),safety:Math.round(safetyScore),headroom:Math.round(headroomScore),freshness:Math.round(clamp(freshnessPct,0,100))}};
}
return{scoreOpportunity};
});