(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;else root.HuntIQOpportunityHealth=api;})(typeof globalThis!=='undefined'?globalThis:this,function(){
'use strict';
const clamp=(n,min=0,max=100)=>Math.min(max,Math.max(min,Number(n)||0));
function historyHealth(o={}){const h=o.timeline||o.history||[];const samples=Number(o.historySampleCount??h.length)||0;let spanDays=Number(o.historySpanDays);if(!Number.isFinite(spanDays)&&h.length>1){const times=h.map(x=>new Date(x.observedAt||x.timestamp||0).getTime()).filter(Number.isFinite).sort((a,b)=>a-b);if(times.length>1)spanDays=Math.round((times[times.length-1]-times[0])/864e5);}if(!Number.isFinite(spanDays))spanDays=0;const score=clamp((samples/14)*55+(spanDays/90)*45);return{samples,spanDays,score:Math.round(score),ready:samples>=6&&spanDays>=21,label:samples>=12&&spanDays>=60?'Deep':samples>=6&&spanDays>=21?'Usable':'Thin'};}
function resaleHealth(o={}){const r=o.resale||{};const sold=Number(o.comps?.soldCount??r.soldCount??0)||0;const confidence=clamp(r.resaleConfidence??o.resaleConfidence);const source=String(r.evidenceType||o.resaleEvidenceType||(sold>0?'verified-sold':'unknown'));const soldBacked=sold>0&&!/ask/i.test(source);const score=Math.round(clamp(confidence*(soldBacked?1:.55)));return{soldCount:sold,confidence,source,soldBacked,score,ready:soldBacked&&confidence>=55};}
function economicsHealth(o={}){const e=o.economics||{};const risk=o.riskAdjustedEconomics||{};const down=o.downsideEconomics||{};const profit=Number(e.profit??o.profit)||0;const roi=Number(e.roi??o.roi)||0;const riskRoi=Number(risk.roi);const downsideRoi=Number(down.roi);const maxBuy=Number(o.purchaseDecision?.maxBuyPrice);const price=Number(o.price??o.observation?.price);const safeBuy=Number.isFinite(maxBuy)&&Number.isFinite(price)?price<=maxBuy:true;const ready=profit>0&&roi>=30&&(!Number.isFinite(riskRoi)||riskRoi>=20)&&(!Number.isFinite(downsideRoi)||downsideRoi>=0)&&safeBuy;return{profit,roi,riskAdjustedRoi:Number.isFinite(riskRoi)?riskRoi:null,downsideRoi:Number.isFinite(downsideRoi)?downsideRoi:null,maxSafeBuy:Number.isFinite(maxBuy)?maxBuy:null,safeBuy,ready};}
function anomalyHealth(o={}){const a=o.anomaly||{};const confidence=clamp(a.confidence??o.confidence);const dropPct=Number(a.dropPct??o.dropPct)||0;const evidence=clamp((o.evidence?.score??o.evidenceQuality??1)*100);const score=Math.round(clamp(confidence*.7+evidence*.3));return{confidence,dropPct,evidence,score,ready:confidence>=55&&evidence>=60};}
function opportunityHealth(o={},opts={}){const history=historyHealth(o),anomaly=anomalyHealth(o),resale=resaleHealth(o),economics=economicsHealth(o);const observedAt=new Date(o.observedAt||o.observation?.observedAt||0).getTime();const now=Number(opts.now||Date.now());const ageMinutes=Number.isFinite(observedAt)&&observedAt>0?Math.max(0,Math.round((now-observedAt)/60000)):Infinity;const fresh=ageMinutes<=(opts.staleAfterMinutes||120);const verified=!!(o.verified??o.observation?.verified??false);const blocks=[];if(!fresh)blocks.push('stale-observation');if(!verified)blocks.push('unverified-source');if(!history.ready)blocks.push('price-history-thin');if(!anomaly.ready)blocks.push('anomaly-evidence-weak');if(!resale.ready)blocks.push('resale-evidence-weak');if(!economics.ready)blocks.push('economics-unsafe');const score=Math.round(clamp(history.score*.2+anomaly.score*.25+resale.score*.25+clamp(Math.min(100,Math.max(0,economics.roi)))*.3));const alertReady=blocks.length===0;return{score,alertReady,state:alertReady?'BUY-READY':fresh?'WATCH':'BLOCKED',blocks,fresh,verified,ageMinutes,history,anomaly,resale,economics};}
return{historyHealth,resaleHealth,economicsHealth,anomalyHealth,opportunityHealth};
});