(function(root){
'use strict';
if(!root.HuntIQPwaOpportunity||!root.HuntIQDataState||typeof deals==='undefined'||typeof renderDeals!=='function')return;
for(const d of deals){
  try{
    d.dataState=root.HuntIQDataState.classifyOpportunityData(d,{asOf:d.observedAt||new Date().toISOString()});
    const strict=root.HuntIQPwaOpportunity.evaluateForPwa(d,d,{asOf:d.observedAt||new Date().toISOString()});
    d.strictEvaluation=strict;d.strictVelocity=strict.velocity||null;d.partialLiquidation=strict.partialLiquidation||null;d.resaleDecay=strict.resaleDecay||null;
    d.retailerSourceReliability=strict.sourceReliability&&strict.sourceReliability.retailer||null;d.resaleSourceReliability=strict.sourceReliability&&strict.sourceReliability.resale||null;d.combinedSourceReliability=strict.sourceReliability&&strict.sourceReliability.combined||null;
    d.sourceAdjustedProfit=strict.economics&&strict.economics.sourceAdjustedProfit!=null?strict.economics.sourceAdjustedProfit:null;d.sourceAdjustedRoi=strict.economics&&strict.economics.sourceAdjustedRoi!=null?strict.economics.sourceAdjustedRoi:null;d.decayAdjustedProfit=strict.economics&&strict.economics.decayAdjustedProfit!=null?strict.economics.decayAdjustedProfit:null;d.decayAdjustedRoi=strict.economics&&strict.economics.decayAdjustedRoi!=null?strict.economics.decayAdjustedRoi:null;d.decisionFloorProfit=strict.economics&&strict.economics.decisionFloorProfit!=null?strict.economics.decisionFloorProfit:null;d.decisionFloorRoi=strict.economics&&strict.economics.decisionFloorRoi!=null?strict.economics.decisionFloorRoi:null;
    d.resalePriceIntegrity=strict.resale&&strict.resale.priceIntegrity!=null?strict.resale.priceIntegrity:null;d.resaleOutlierCount=strict.resale&&strict.resale.outlierCount!=null?strict.resale.outlierCount:null;d.resaleFreshnessScore=strict.resale&&strict.resale.resaleFreshnessScore!=null?strict.resale.resaleFreshnessScore:null;d.newestCompletedSaleAgeDays=strict.resale&&strict.resale.newestSaleAgeDays!=null?strict.resale.newestSaleAgeDays:null;d.medianCompletedSaleAgeDays=strict.resale&&strict.resale.medianSaleAgeDays!=null?strict.resale.medianSaleAgeDays:null;
    const acq=strict.economics&&strict.economics.acquisition||null;d.multiBuyPromotion=acq&&acq.multiBuyPromotion||null;d.multiBuyDiscount=acq&&acq.multiBuyDiscount!=null?acq.multiBuyDiscount:null;
    if(strict.resale&&strict.resale.marketValue>0)d.market=strict.resale.marketValue;if(strict.economics&&strict.economics.riskAdjustedProfit!=null)d.profit=strict.economics.riskAdjustedProfit;if(strict.economics&&strict.economics.riskAdjustedRoi!=null)d.roi=strict.economics.riskAdjustedRoi;
    const customerAlertEligible=strict.evidence.alertEligible&&d.dataState.alertEligible;
    const dataBlocker=d.dataState.alertEligible?[]:[d.dataState.reason||'customer-data-state'];
    d.strictRecommendation=strict.recommendation;d.alert={...(d.alert||{}),alert:customerAlertEligible,priority:customerAlertEligible?(strict.evidence.alertLevel||'standard'):'suppressed',strict:true,blockers:[...(strict.evidence.blockers||[]),...dataBlocker],warnings:strict.evidence.warnings||[]};
  }catch(err){d.strictEvaluationError=String(err&&err.message||err);}
}
const pct=v=>v==null?'n/a':`${Math.round(Number(v))}%`;const dollars=v=>v==null?'n/a':new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(Number(v));
function promotionLine(d){const p=d.multiBuyPromotion;if(!p)return'';const limit=p.redemptionLimit==null?'none stated':p.redemptionLimit;return `<br><strong>Quantity offer</strong>: ${p.type} · eligible units: ${p.eligibleUnitCount} · redemptions applied: ${p.appliedRedemptions}/${p.availableRedemptions} · limit: ${limit} · mix & match: ${p.mixAndMatch?'yes':'no'} · savings: ${dollars(d.multiBuyDiscount)} · effective item cost: ${dollars(p.currentItemEffectiveCost)}${p.currentItemEffectiveUnitCost?` (${dollars(p.currentItemEffectiveUnitCost)}/unit)`:''}`;}
function liquidationLine(d){const p=d.partialLiquidation;if(!p)return'';const h=p.horizons||[];const f=days=>h.find(x=>x.days===days)||{};return `<br><strong>Capital release</strong>: 30d ${f(30).expectedUnitsSold||0}/${p.purchaseQuantity} sold · ${dollars(f(30).capitalTiedUp)} tied up; 60d ${f(60).expectedUnitsSold||0}/${p.purchaseQuantity} sold · ${dollars(f(60).capitalTiedUp)} tied up; 90d ${f(90).expectedUnitsSold||0}/${p.purchaseQuantity} sold · ${dollars(f(90).capitalTiedUp)} tied up (${pct(p.capitalAtRisk90Pct)} of buy capital) · exposure: ${p.band}`;}
function decayLine(d){const p=d.resaleDecay;if(!p)return'';return `<br><strong>Resale decay stress</strong>: trend 30d vs 90d ${p.trend30vs90Pct==null?'n/a':pct(p.trend30vs90Pct)} · monthly stress ${pct(p.monthlyDecayPct)} · 30/60/90 exit ${dollars(p.prices&&p.prices.d30)} / ${dollars(p.prices&&p.prices.d60)} / ${dollars(p.prices&&p.prices.d90)} · weighted exit ${dollars(p.weightedSalePrice)} (${pct(p.weightedDecayPct)} below current) · decay-adjusted ROI ${pct(d.decayAdjustedRoi)}`;}
function decorateDetails(){document.querySelectorAll('#dealGrid .deal-card').forEach(card=>{const title=card.querySelector('h3')&&card.querySelector('h3').textContent;const retailer=card.querySelector('.retailer')&&card.querySelector('.retailer').textContent;const d=deals.find(x=>x.title===title&&x.retailer===retailer);const panel=card.querySelector('.comp-panel');if(!d||!panel||panel.querySelector('.strict-evidence'))return;const block=document.createElement('div');block.className='strict-evidence';block.innerHTML=`<br><strong>HUNTIQ strict evidence</strong><br>Retailer source reliability: ${pct(d.retailerSourceReliability&&d.retailerSourceReliability.score)} · Resale source reliability: ${pct(d.resaleSourceReliability&&d.resaleSourceReliability.score)} · Combined: ${pct(d.combinedSourceReliability&&d.combinedSourceReliability.score)}<br>Resale integrity: ${pct(d.resalePriceIntegrity)} · filtered outliers: ${d.resaleOutlierCount==null?'n/a':d.resaleOutlierCount} · freshness: ${pct(d.resaleFreshnessScore)} · newest sold comp: ${d.newestCompletedSaleAgeDays==null?'n/a':Math.round(d.newestCompletedSaleAgeDays)+'d'}<br>Source-adjusted profit: ${dollars(d.sourceAdjustedProfit)} · source-adjusted ROI: ${pct(d.sourceAdjustedRoi)} · <strong>decision-floor profit: ${dollars(d.decisionFloorProfit)} · ROI: ${pct(d.decisionFloorRoi)}</strong>${promotionLine(d)}${liquidationLine(d)}${decayLine(d)}<br>Alert: ${d.alert&&d.alert.priority||'suppressed'}${d.alert&&d.alert.blockers&&d.alert.blockers.length?` · blockers: ${d.alert.blockers.join(', ')}`:''}${d.alert&&d.alert.warnings&&d.alert.warnings.length?` · warnings: ${d.alert.warnings.join(', ')}`:''}`;panel.appendChild(block);});}
function decorateDataStates(){
  document.querySelectorAll('#dealGrid .deal-card').forEach(card=>{
    const title=card.querySelector('h3')&&card.querySelector('h3').textContent;const retailer=card.querySelector('.retailer')&&card.querySelector('.retailer').textContent;const d=deals.find(x=>x.title===title&&x.retailer===retailer);const top=card.querySelector('.deal-top');
    if(!d||!top||top.querySelector('.data-state-badge'))return;
    const badge=document.createElement('span');badge.className=`data-state-badge ${d.dataState.kind}`;badge.textContent=d.dataState.label;badge.title=d.dataState.kind==='live'?'Validated, fresh provider observation':'Not eligible for live alerts';top.insertBefore(badge,top.querySelector('.badge'));
  });
}
const filters=document.querySelector('.filters');
if(filters&&!filters.querySelector('[data-filter="demo"]')){
  for(const [key,label] of [['live','Live'],['demo','Demo']]){const button=document.createElement('button');button.className='filter';button.dataset.filter=key;button.textContent=label;button.addEventListener('click',()=>{document.querySelectorAll('.filter').forEach(b=>b.classList.remove('active'));button.classList.add('active');active=key;renderDeals();decorateDataStates();});filters.append(button);}
}
const opportunitySection=document.querySelector('#opportunities .section-head');
if(opportunitySection&&!document.querySelector('.customer-data-status')){const counts=deals.reduce((m,d)=>(m[d.dataState.kind]=(m[d.dataState.kind]||0)+1,m),{});const status=document.createElement('div');status.className='customer-data-status';status.innerHTML=`<strong>${counts.live||0} live</strong><span>${counts.cached||0} cached</span><span>${counts.delayed||0} delayed</span><span>${counts.demo||0} demo</span><small>Validation-only provider observations stay hidden and cannot alert.</small>`;opportunitySection.insertAdjacentElement('afterend',status);}
renderDeals();decorateDetails();decorateDataStates();const grid=document.querySelector('#dealGrid');if(grid&&typeof MutationObserver!=='undefined')new MutationObserver(()=>{decorateDetails();decorateDataStates();}).observe(grid,{childList:true,subtree:true});
})(typeof globalThis!=='undefined'?globalThis:this);
