(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;root.HuntIQQuality=api;})(typeof globalThis!=='undefined'?globalThis:this,function(){
'use strict';
const clamp=(n,min,max)=>Math.min(max,Math.max(min,Number(n)||0));
const SOURCE_WEIGHTS={retailer:1,'retailer-api':1,'retailer-page':0.96,'official-affiliate':0.92,'marketplace-sold':0.9,'marketplace-api':0.9,'community-verified':0.76,community:0.58,unknown:0.45,demo:1,'demo-current':1,'demo-history':1};
function sourceWeight(source='unknown'){const key=String(source||'unknown').toLowerCase();return SOURCE_WEIGHTS[key]==null?SOURCE_WEIGHTS.unknown:SOURCE_WEIGHTS[key];}
function ageHours(observedAt,now=Date.now()){const t=new Date(observedAt||0).getTime();if(!Number.isFinite(t)||t<=0)return Infinity;return Math.max(0,(Number(now)-t)/36e5);}
function freshnessWeight(observedAt,{now=Date.now(),halfLifeHours=24,maxAgeHours=168}={}){const age=ageHours(observedAt,now);if(!Number.isFinite(age)||age>maxAgeHours)return 0;const half=Math.max(1,Number(halfLifeHours)||24);return +Math.pow(0.5,age/half).toFixed(4);}
function evidenceQuality({source='unknown',observedAt,baseQuality=1,verified=false,now=Date.now(),halfLifeHours=24,maxAgeHours=168}={}){const sourceScore=sourceWeight(source);const fresh=freshnessWeight(observedAt,{now,halfLifeHours,maxAgeHours});const verification=verified?1:0.88;const score=clamp(Number(baseQuality)==null?1:Number(baseQuality),0,1)*sourceScore*fresh*verification;return{score:+clamp(score,0,1).toFixed(3),sourceScore:+sourceScore.toFixed(2),freshnessScore:+fresh.toFixed(3),ageHours:Number.isFinite(ageHours(observedAt,now))?+ageHours(observedAt,now).toFixed(1):null,verified:Boolean(verified),stale:fresh<0.25};}
function combineEvidence(items=[]){const rows=items.map(evidenceQuality).filter(x=>Number.isFinite(x.score));if(!rows.length)return{score:0,count:0,staleCount:0};const sorted=rows.map(x=>x.score).sort((a,b)=>b-a);const top=sorted.slice(0,3);const score=top.reduce((s,v,i)=>s+v*(i===0?.6:i===1?.27:.13),0)/(top.length===1?.6:top.length===2?.87:1);return{score:+clamp(score,0,1).toFixed(3),count:rows.length,staleCount:rows.filter(x=>x.stale).length};}
return{SOURCE_WEIGHTS,sourceWeight,ageHours,freshnessWeight,evidenceQuality,combineEvidence};
});