(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;root.HuntIQRisk=api;})(typeof globalThis!=='undefined'?globalThis:this,function(){
'use strict';
const clamp=(n,min,max)=>Math.min(max,Math.max(min,Number(n)||0));
const median=values=>{const a=(values||[]).map(Number).filter(Number.isFinite).sort((x,y)=>x-y);if(!a.length)return null;const m=Math.floor(a.length/2);return a.length%2?a[m]:(a[m-1]+a[m])/2;};
function priceStability(history=[]){const prices=(history||[]).map(Number).filter(n=>Number.isFinite(n)&&n>0);if(prices.length<3)return{sampleSize:prices.length,medianPrice:median(prices),madPct:null,rangePct:null,stabilityScore:50,label:'Insufficient History'};const med=median(prices);const abs=prices.map(v=>Math.abs(v-med));const mad=median(abs)||0;const madPct=med>0?(mad/med)*100:0;const rangePct=med>0?((Math.max(...prices)-Math.min(...prices))/med)*100:0;const penalty=clamp(madPct*4+rangePct*.8,0,100);const stabilityScore=Math.round(clamp(100-penalty,0,100));const label=stabilityScore>=85?'Very Stable':stabilityScore>=70?'Stable':stabilityScore>=50?'Variable':'Highly Volatile';return{sampleSize:prices.length,medianPrice:+med.toFixed(2),madPct:+madPct.toFixed(1),rangePct:+rangePct.toFixed(1),stabilityScore,label};}
function stabilityAdjustedAnomaly(anomaly={},history=[]){const stability=priceStability(history);const raw=clamp(anomaly.confidence,0,99);const factor=.55+.45*(stability.stabilityScore/100);const confidence=Math.round(clamp(raw*factor,0,99));let label=anomaly.label||'Normal Price';if(confidence<65&&['Probable Error','Extreme Deal'].includes(label))label=Number(anomaly.dropPct)>=20?'Markdown Watch':'Normal Price';else if(confidence<85&&label==='Probable Error')label='Extreme Deal';return{...stability,rawConfidence:raw,confidence,confidenceFactor:+factor.toFixed(3),label};}
function liquidationValue(resale={}){const conservative=Math.max(0,Number(resale.conservativeValue)||0);const liquidity=clamp(resale.liquidityScore==null?50:resale.liquidityScore,0,100);const spread=Math.max(0,Number(resale.spreadPct)||0);const momentum=clamp(resale.momentumScore==null?50:resale.momentumScore,0,100);const liquidityHaircut=(100-liquidity)*.0018;const spreadHaircut=Math.min(.12,spread*.0015);const momentumHaircut=momentum<50?(50-momentum)*.0012:0;const haircut=clamp(.05+liquidityHaircut+spreadHaircut+momentumHaircut,.05,.35);return{value:+(conservative*(1-haircut)).toFixed(2),haircutPct:+(haircut*100).toFixed(1),liquidityScore:liquidity,spreadPct:spread,momentumScore:momentum};}
function stressEconomics(economicsFn,input={},resale={}){if(typeof economicsFn!=='function')throw new Error('economics function required');const liquidation=liquidationValue(resale);const args={buyPrice:input.price,marketValue:liquidation.value,feeRate:input.feeRate,shipping:input.shipping,taxRate:input.taxRate,miscCost:input.miscCost,holdingDays:input.holdingDays==null?(resale.estimatedDaysToSell||0):input.holdingDays,holdingCostPerDay:input.holdingCostPerDay};const econ=economicsFn(args);return{...liquidation,economics:econ};}
function evaluateRisk(opportunity={},economicsFn){const stability=stabilityAdjustedAnomaly(opportunity.anomaly||{},opportunity.priceHistory||[]);const liquidation=stressEconomics(economicsFn,opportunity,opportunity.resale||{});return{priceStability:stability,stabilityAdjustedAnomalyConfidence:stability.confidence,stabilityAdjustedAnomalyLabel:stability.label,liquidation};}
return{median,priceStability,stabilityAdjustedAnomaly,liquidationValue,stressEconomics,evaluateRisk};
});