(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;root.HuntIQSnapshots=api;})(typeof globalThis!=='undefined'?globalThis:this,function(){
'use strict';
const DB_NAME='huntiq_history_fast';const DB_VERSION=1;const STORE='latest_snapshots';
const productKey=o=>`${String(o.retailer||'').trim()}|${String(o.sku||o.id||'').trim()}|${String(o.storeId||'online')}`;
function normalizeSnapshot(o={}){return{product:productKey(o),retailer:String(o.retailer||'').trim(),sku:String(o.sku||o.id||'').trim(),storeId:String(o.storeId||'online'),price:Number(o.price),inventory:o.inventory==null?null:Number(o.inventory),observedAt:o.observedAt||new Date().toISOString(),verified:Boolean(o.verified),evidenceQuality:o.evidenceQuality==null?null:Number(o.evidenceQuality),confirmationScore:o.confirmationScore==null?null:Number(o.confirmationScore),source:o.source||'unknown',sourceFamily:o.sourceFamily||null};}
function openDb(){return new Promise((resolve,reject)=>{if(typeof indexedDB==='undefined')return reject(new Error('IndexedDB unavailable'));const req=indexedDB.open(DB_NAME,DB_VERSION);req.onupgradeneeded=()=>{const db=req.result;if(!db.objectStoreNames.contains(STORE)){const s=db.createObjectStore(STORE,{keyPath:'product'});s.createIndex('retailer','retailer',{unique:false});s.createIndex('observedAt','observedAt',{unique:false});s.createIndex('verified','verified',{unique:false});}};req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error);});}
async function saveSnapshot(input){const row=normalizeSnapshot(input);if(!row.retailer||!row.sku||!Number.isFinite(row.price))throw new Error('retailer, sku and numeric price are required');const db=await openDb();const existing=await new Promise((resolve,reject)=>{const tx=db.transaction(STORE,'readonly');const req=tx.objectStore(STORE).get(row.product);req.onsuccess=()=>resolve(req.result||null);req.onerror=()=>reject(req.error);});if(existing&&new Date(existing.observedAt)>new Date(row.observedAt)){db.close();return existing;}await new Promise((resolve,reject)=>{const tx=db.transaction(STORE,'readwrite');tx.objectStore(STORE).put(row);tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error);});db.close();return row;}
async function getSnapshot(match={}){const db=await openDb();const key=productKey(match);const row=await new Promise((resolve,reject)=>{const tx=db.transaction(STORE,'readonly');const req=tx.objectStore(STORE).get(key);req.onsuccess=()=>resolve(req.result||null);req.onerror=()=>reject(req.error);});db.close();return row;}
async function getRetailerSnapshots(retailer){const db=await openDb();const rows=await new Promise((resolve,reject)=>{const tx=db.transaction(STORE,'readonly');const req=tx.objectStore(STORE).index('retailer').getAll(String(retailer||''));req.onsuccess=()=>resolve(req.result||[]);req.onerror=()=>reject(req.error);});db.close();return rows.sort((a,b)=>new Date(b.observedAt)-new Date(a.observedAt));}
return{productKey,normalizeSnapshot,saveSnapshot,getSnapshot,getRetailerSnapshots};
});