(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;root.HuntIQSnapshots=api;})(typeof globalThis!=='undefined'?globalThis:this,function(){
'use strict';
const DB_NAME='huntiq_history_fast';const DB_VERSION=2;const STORE='latest_snapshots';const HISTORY_STORE='price_observations';
const productKey=o=>`${String(o.retailer||'').trim()}|${String(o.sku||o.id||'').trim()}|${String(o.storeId||'online')}`;
function isoTime(value){const d=value?new Date(value):new Date();return Number.isFinite(d.getTime())?d.toISOString():new Date().toISOString();}
function normalizeSnapshot(o={}){return{product:productKey(o),retailer:String(o.retailer||'').trim(),sku:String(o.sku||o.id||'').trim(),storeId:String(o.storeId||'online'),price:Number(o.price),inventory:o.inventory==null?null:Number(o.inventory),observedAt:isoTime(o.observedAt),verified:Boolean(o.verified),evidenceQuality:o.evidenceQuality==null?null:Number(o.evidenceQuality),confirmationScore:o.confirmationScore==null?null:Number(o.confirmationScore),source:o.source||'unknown',sourceFamily:o.sourceFamily||null};}
function observationId(row){return`${row.product}|${row.observedAt}|${Number(row.price).toFixed(4)}|${String(row.source||'unknown')}`;}
function normalizeObservation(input={}){const row=normalizeSnapshot(input);return{...row,id:observationId(row)};}
function openDb(){return new Promise((resolve,reject)=>{if(typeof indexedDB==='undefined')return reject(new Error('IndexedDB unavailable'));const req=indexedDB.open(DB_NAME,DB_VERSION);req.onupgradeneeded=()=>{const db=req.result;if(!db.objectStoreNames.contains(STORE)){const s=db.createObjectStore(STORE,{keyPath:'product'});s.createIndex('retailer','retailer',{unique:false});s.createIndex('observedAt','observedAt',{unique:false});s.createIndex('verified','verified',{unique:false});}if(!db.objectStoreNames.contains(HISTORY_STORE)){const h=db.createObjectStore(HISTORY_STORE,{keyPath:'id'});h.createIndex('product','product',{unique:false});h.createIndex('retailer','retailer',{unique:false});h.createIndex('observedAt','observedAt',{unique:false});}};req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error);});}
async function saveSnapshot(input){const row=normalizeSnapshot(input);if(!row.retailer||!row.sku||!Number.isFinite(row.price))throw new Error('retailer, sku and numeric price are required');const observation=normalizeObservation(row);const db=await openDb();const existing=await new Promise((resolve,reject)=>{const tx=db.transaction(STORE,'readonly');const req=tx.objectStore(STORE).get(row.product);req.onsuccess=()=>resolve(req.result||null);req.onerror=()=>reject(req.error);});const latest=existing&&new Date(existing.observedAt)>new Date(row.observedAt)?existing:row;await new Promise((resolve,reject)=>{const tx=db.transaction([STORE,HISTORY_STORE],'readwrite');if(latest===row)tx.objectStore(STORE).put(row);tx.objectStore(HISTORY_STORE).put(observation);tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error);});db.close();return latest;}
async function saveObservation(input){const row=normalizeObservation(input);if(!row.retailer||!row.sku||!Number.isFinite(row.price))throw new Error('retailer, sku and numeric price are required');const db=await openDb();await new Promise((resolve,reject)=>{const tx=db.transaction(HISTORY_STORE,'readwrite');tx.objectStore(HISTORY_STORE).put(row);tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error);});db.close();return row;}
async function getSnapshot(match={}){const db=await openDb();const key=productKey(match);const row=await new Promise((resolve,reject)=>{const tx=db.transaction(STORE,'readonly');const req=tx.objectStore(STORE).get(key);req.onsuccess=()=>resolve(req.result||null);req.onerror=()=>reject(req.error);});db.close();return row;}
async function getRetailerSnapshots(retailer){const db=await openDb();const rows=await new Promise((resolve,reject)=>{const tx=db.transaction(STORE,'readonly');const req=tx.objectStore(STORE).index('retailer').getAll(String(retailer||''));req.onsuccess=()=>resolve(req.result||[]);req.onerror=()=>reject(req.error);});db.close();return rows.sort((a,b)=>new Date(b.observedAt)-new Date(a.observedAt));}
async function getPriceHistory(match={},options={}){const key=productKey(match);const now=options.now?new Date(options.now):new Date();const since=options.since?new Date(options.since):null;const maxAgeDays=Number(options.maxAgeDays);const cutoff=since&&Number.isFinite(since.getTime())?since:(Number.isFinite(maxAgeDays)&&maxAgeDays>=0?new Date(now.getTime()-maxAgeDays*86400000):null);const db=await openDb();const rows=await new Promise((resolve,reject)=>{const tx=db.transaction(HISTORY_STORE,'readonly');const req=tx.objectStore(HISTORY_STORE).index('product').getAll(key);req.onsuccess=()=>resolve(req.result||[]);req.onerror=()=>reject(req.error);});db.close();return rows.filter(row=>{const t=new Date(row.observedAt);return Number.isFinite(t.getTime())&&t<=now&&(!cutoff||t>=cutoff);}).sort((a,b)=>new Date(a.observedAt)-new Date(b.observedAt));}
return{DB_NAME,DB_VERSION,STORE,HISTORY_STORE,productKey,normalizeSnapshot,observationId,normalizeObservation,saveSnapshot,saveObservation,getSnapshot,getRetailerSnapshots,getPriceHistory};
});