create table if not exists marketplace_cost_floor_assessments (
  id integer primary key,
  opportunity_id text,
  marketplace text,
  assessed_at text not null default current_timestamp,
  sale_price real not null,
  acquisition_cost real not null,
  marketplace_fee_pct real not null,
  marketplace_fee real not null,
  payment_fee real not null,
  fulfillment_cost real not null,
  return_reserve_pct real not null,
  return_reserve real not null,
  tax_drag real not null,
  net_profit real not null,
  roi_pct real not null,
  margin_pct real not null,
  evidence_score integer not null,
  evidence_haircut_pct real not null,
  evidence_adjusted_profit real not null,
  evidence_adjusted_roi_pct real not null,
  min_net_profit real not null,
  min_roi_pct real not null,
  eligible_for_urgent_alert integer not null,
  stressed_alert_state text not null,
  warnings_json text not null default '[]',
  blockers_json text not null default '[]'
);
create index if not exists idx_marketplace_cost_floor_opportunity on marketplace_cost_floor_assessments(opportunity_id, assessed_at);