create table if not exists alert_material_change_assessments (
  id integer primary key autoincrement,
  opportunity_id text not null,
  retailer text,
  store_id text,
  assessed_at text not null,
  previous_alert_at text,
  previous_price real,
  current_price real,
  previous_profit real,
  current_profit real,
  previous_roi real,
  current_roi real,
  previous_confidence real,
  current_confidence real,
  previous_anomaly_score real,
  current_anomaly_score real,
  previous_history_sample_count integer,
  current_history_sample_count integer,
  previous_resale_median real,
  current_resale_median real,
  previous_resale_effective_weight real,
  current_resale_effective_weight real,
  previous_recommended_quantity integer,
  current_recommended_quantity integer,
  previous_available_quantity integer,
  current_available_quantity integer,
  material_change_score real not null,
  materially_changed integer not null check (materially_changed in (0,1)),
  alert_decision text not null,
  decision_reason text not null,
  reasons_json text not null default '[]',
  metrics_json text not null default '{}',
  created_at text not null default current_timestamp
);
create index if not exists idx_alert_material_change_opportunity_time on alert_material_change_assessments(opportunity_id, assessed_at desc);
create index if not exists idx_alert_material_change_decision on alert_material_change_assessments(alert_decision, assessed_at desc);